### ISSUE TITLE
remove gulp dependencies from preboot/server

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#105]
I want to be able to `require('universal/preboot/server')` without gulp

**Comment by gdi2290** [comment]
I need to generate the preboot code as a string

```es6
var preboot = require('universal/preboot/server');
var clientCode = preboot.generateClientCodeAsString(/* opts */);
```

**Comment by jeffwhelpley** [comment]
Let's talk about this more. We may not need this. `preboot.getClientCode()` already returns a string. We can probably move Gulp to a dev dependency because it is not referenced anywhere in the server code (only gulp plugins are referenced). 

Taking a step back here, though, what is the goal? It shouldn't really matter what dependencies there are on the server side. But, I may be missing something.

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/pull/117

**Comment by gdi2290** [comment]
merged via https://github.com/angular/universal/commit/710dca739a28a179313d0db0697f6488c267326f
