### ISSUE TITLE
follow up with ASP.NET and merge fixes

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#123]
We need to merge the fixes for router-outlet

**Comment by jeffbcross** [comment]
@gdi2290 or @jeffwhelpley could one of you provide more context here? Has this been fixed upsteam?

**Comment by gdi2290** [comment]
cc @SteveSanderson

**Comment by jeffwhelpley** [comment]
Context is that Steve fixes some issues with the use of the Router on the server. I don't remember the specific issue.

**Comment by SteveSandersonMS** [comment]
I applied my changes in a fork here: https://github.com/SteveSandersonMS/universal/commits/master - do you want to have a look and see which of them are applicable to recreate in the original repo? These changes are based on a pretty recent version of angular-universal.

Details:
 * `efca97` is a rough sketch of integrating with Angular's current `http` APIs and is sufficient to make my current prototypes work. However, *there's still a race condition here* - for some reason (on rare occasions) it still renders the page before waiting for the request. I'm guessing that the `this._ngZone.run` stuff is not really right.
 * `ab82e4` is needed otherwise `<router-outlet>` will throw an exception because it can't figure out the root component type
 * `a83959` is needed to make the routing system able to receive and interpret the BASE_URL passed in from the Node app host (so it can show the relevant part of the app matching the URL)
 * `566351` works around the problem I mentioned with `src` attributes being stripped from `<img>` tags (and presumably other elements with `src` attributes). I'm not 100% clear on whether this is the right solution, but I guess you'll know.

No doubt you'll have better insight on how best to integrate these changes (and what tests are needed, etc.).

**Comment by jeffwhelpley** [comment]
@gdi2290 if you can take a look at Steve's changes before our meeting today so we can figure out which can be pulled over here.

**Comment by gdi2290** [comment]
I merged all of them except the first one https://github.com/SteveSandersonMS/universal/commit/efca974046f9010c6d12efb9010e5fe5af1a14ee that I need to look into more

**Comment by jeffwhelpley** [comment]
@gdi2290 can we close this out with the router-outlet fix you put in yesterday?

**Comment by gdi2290** [comment]
yup
