### ISSUE TITLE
Better development experience for the starter repo 

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#125]
We need a great workflow for people developing universal components in our [universal-starter](https://github.com/angular/universal-starter) repo.

- [ ] livereload server
- [ ] livereload client

Currently the developer would have to maintain two processes one to build the client files and the other for the server (assuming they use typescript). For the server we're currently using [`ts-node`](https://github.com/TypeStrong/ts-node) which allow the user to skip having to worry about building TypeScript files. The problem with that is trying to understand how that plays with other modules in the javascript ecosystem. For example, `nodemon` is a popular module that node developers use when developing their applications. With `ts-node` you would have include an `execMap` as well as include `ts` as files to be watched

**Comment by tamascsaba** [comment]
Hy,

I use [ereqt](https://github.com/jsen-/ereqt/ ) or [tpyescript-require](https://github.com/theblacksmith/typescript-require) instead of ts-node.
* typescript-require is much quicker, but oldest and not maintain
* ereqt create cached modules with you can debug with VS or Webstrom (which editor has source map support debug)

**Comment by gdi2290** [comment]
I removed ts-node in favor for webpack for both client/server. The only other problem is live reloading both client/server.
