### ISSUE TITLE
configure browsersync options at project root level.

### ISSUE THREAD

**Issue by laurencefass** [angular/universal#1402]
# Feature Request

#### What is the desired behavior?

i'm comparing @universal against Razzle, Next and Nuxt which all provide webpack configuration in root folder by default. i cant imagine using these without this utility as its impossible to know ahead what config i might need for a particular installation.

currently browsersync is configured in @universal/builders/src/ssr-dev-server/index.js. state buried in a module limits possible use cases.

enable configure browsersync options in a file at the root of the project by injecting options into the universal bundle.

#### What is the use-case or motivation for the desired behavior?
a multitude of use-cases.

#### Is there anything else we should know?
no

**Comment by alan-agius4** [comment]
Hi, thanks for this request. I personally think that similarly to the Angular CLI  were webpack configurations are not exposed, so should browsersync configuration.

The main reasons are;
1) Changing a single setting might break live-reloading, and it would be very difficult to provide support in that aspect.
2) If we choose to replace browsersync with something else in the future it will become a break change, which will be undesirable.

If you feel, that there is a use-case which currently is not handled, please feel free to describe it and we'd evaluate whether we should support it.

**Comment by laurencefass** [comment]
My current use case is running angular on http://domain.com/myapp/ behind an reverse proxy which could be better configured with app access to [socket option](https://www.browsersync.io/docs/options#option-socket) and/or [script-path option](https://www.browsersync.io/docs/options#option-scriptPath)

**Comment by alan-agius4** [comment]
For the case above, I think it's simpler for the user to use the `public-host` option, which users are already accustomed too with the Angular CLI.

In that particular use case changing the browser-sync socket option and script option would not be enough, as another reverse proxy would need to be set up.  This is because browser-sync + socket.io don't support public-host which contain pathnames. Example: `http://foo.com/ssr`. And in such case, it's easier for the builder to setup the correct options include a proxy middleware rather than leaving developers wonder how to get it working.

So for instance when using nginx, apart from the normal reverse proxy
```
location /ssr/ {
    proxy_pass      http://localhost:4200/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}
```
Users would also need to add another reverse proxy for socket.io
```
location /ssr/browser-sync/socket.io {
    proxy_pass      http://localhost:4200/ssr/browser-sync/socket.io;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}
```

I think that the above would be undesirable.

**Comment by alan-agius4** [comment]
Also, exposing such config would also make it harder to merge with the
default config.

Example if a user provides a middleware or proxy should it inserted prior,
after or replace the default one.

**Comment by laurencefass** [comment]
thanks for feedback just sharing experience from use of non-angular config for same use-case.

to check my understanding: is it currently **not** possible to access app using reverse proxy to /domain/app-path? i.e. do we need implementation of public host for this to work?

**Comment by alan-agius4** [comment]
Yeah, you need to use the public-host option

**Comment by alan-agius4** [comment]
Closing as per above convo.
