### ISSUE TITLE
Starting a new Project

### ISSUE THREAD

**Issue by daslicht** [angular/universal#143]
Hi,
is it possible to start an Angular 2 App as client side only and later transform it as Universal App?
What do I need to be aware of ?
Or is it better to start as Universal App?

**Comment by episodeyang** [comment]
I'm in the same boat. This is really badly needed on our part.

**Comment by mcpDESIGNS** [comment]
If I'm not mistake I believe you could do that. 
You would later set up your ng2engine view rendering in Node later on.

Everything still being in beta, I don't know how serious of a project I would make using Angular 2 just yet though since everything could change in the next few months, just be careful!

**Comment by daslicht** [comment]
Yeah it's on hold here

**Comment by daslicht** [comment]
jsblocks look more interesting to us atm

**Comment by mcpDESIGNS** [comment]
Never seen that, looks pretty nice too! When are they releasing a production ready version, any idea?

**Comment by daslicht** [comment]
no idea, the interesting part of this project is that it comes with serverside rendering out of the box.
Feel free to join the gitter chat :)
