### ISSUE TITLE
Poor Performance & Page speed with Angular Universal

### ISSUE THREAD

**Issue by captainjackrana** [angular/universal#1448]
Google Pagespeed Insights reveals a very poor score on performance for pages that are served with SSR via Angular Universal.

The app is built on top of the **ngx-admin** Angular template. ( https://github.com/akveo/ngx-admin), where we've tried implementing universal SSR.

Most of the performance alerts are attributed to the category of "Main Thread Work", which means that there is javascript & css execution happening after the page is rendered.

![Screen Shot 2020-01-13 at 8 10 56 PM](https://user-images.githubusercontent.com/5394402/72356513-65317a80-370f-11ea-8069-09c820df1f22.png)

![Screen Shot 2020-01-13 at 8 11 11 PM](https://user-images.githubusercontent.com/5394402/72356479-58148b80-370f-11ea-9c18-15fd747468bb.png)

We do not see this recommendation for our current SSR solution, an in-house **Prerender.io** hosting which internally uses a headless chrome to serve the rendered page. 

Also, Pagespeed reports a higher performance score for Prerender based SSR, even though it has higher network latency involved. One reason for this could be that Prerender has a mechanism to strip out `<script>` tags from the html which ensures that no javascript gets executed from the client browser accidentally.

How do we optimize the Universal implementation for a good performance score?

**Comment by alan-agius4** [comment]
Hi @captainjackrana, it is expected that `prerender.io` has a better performance score, and it’s for the same reasons that you mentioned.

The fact that it strips out `script` tags so their is almost zero javascript to be executed on the client side. With this approach the client application is never bootstrapped. While this does perform better in terms or performance score you are no longer having a PWA which is undesirable. As for each page change you will go back to the server to render the application.

**Comment by mvgadagi** [comment]
Yes even I wanted to ask this question, is there a way to have web worker support for the Angular Universal

**Comment by CarlosTorrecillas** [comment]
Me too, if there are any tips about how to improve the performance here I would be really thankful

**Comment by CaerusKaru** [comment]
We're going to revamp the docs experience for Universal in the coming months, but performance tips usually boil down to "limit activity on initial render", any setTimeout/setInterval calls or other Observable macrotasks, or heavy UI interaction. Heavy applications will always be heavy, SSR for Universal is generally pretty quick if you avoid the major server-side pitfalls. But as @alan-agius4 mentioned, Prerender.io is faster specifically because they don't do client-side bootstrapping. So the question _really_ is, how do I make my application faster, not how do I make my Universal application faster.
