### ISSUE TITLE
Prerender `--routes` argument is required even if no `RouterModule` is used

### ISSUE THREAD

**Issue by edbzn** [angular/universal#1452]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

No.

### Description

Hi, 

I noticed something that I feel confusing about prerendering. My Angular application needs one single route, so I'm not using the `RouterModule`. I want to prerender the application using the new prerender command:

```bash
ng run my-app:prerender
```

Which get me the following error: 

```
An unhandled exception occurred: No routes found.
```

To make this work I need to specify an empty `--routes` argument in the command.

```bash
ng run my-app:prerender --routes
```

This argument is required even if I have no `RouterModule` declared. Is it a desired behavior?

## 🌍 Your Environment

```
@nguniversal/builders             9.0.0-rc.0
@nguniversal/common               9.0.0-rc.0
@nguniversal/express-engine       9.0.0-rc.0
```

**Comment by alan-agius4** [comment]
@edbzn, at the moment routing and RouterModule are required to generate prerendering.

**Comment by edbzn** [comment]
@alan-agius4, I generated a pre-rendered build without the `RouterModule`, and it works. The problem is that it fails if I do not specify the `--routes` argument, which is weird when having no routes. I'm willing to fix it if you think it should be.

**Comment by wagnermaciel** [comment]
Hey @edbzn I'm trying to understand this use case more clearly - it seems like you're trying to prerender just "/", correct?

@alan-agius4 do you think it would be more intuitive if we checked for a `RouterModule` and if we could not find one just prerender the index?

**Comment by alan-agius4** [comment]
I think actually all we need to do here is to remove the validation that checks the length of the array. Since without any route it seems that the index is rendered.

We can check the presence of a RouterModule via AST.

Overall, I’d like to understand a bit better the use case of prerendering a non routed it and is this something which is done often or it’s just a one time case.

**Comment by wagnermaciel** [comment]
@alan-agius4 I'm not sure of this but I think specifying a single argument `--routes` is the equivalent of specifying one empty string route which is inferred to be "/", which is why the command succeeds. Not providing any routes will fail

**Comment by wagnermaciel** [comment]
Did some investigation. `ng run app:prerender --routes` is the equivalent of specifying a single route as "". We just pass this into this as a render option and "" and "/" are treated the same - rendering index.

https://github.com/angular/universal/blob/master/modules/builders/src/prerender/render.ts#L55

**Here's how I determined this:**

I logged:
![Screen Shot 2020-01-21 at 9 52 13 AM](https://user-images.githubusercontent.com/25158423/72829629-fc2c9400-3c33-11ea-88a2-699cef325a80.png)
Result:
![Screen Shot 2020-01-21 at 9 48 35 AM](https://user-images.githubusercontent.com/25158423/72829339-6f81d600-3c33-11ea-9956-61c79d45dbb2.png)

**Comment by edbzn** [comment]
I think that a one page application without routing is more than a one time scenario. It's pretty common for simple websites (e.g. landing pages). It can improve the developer experience for this use case.

**Comment by wagnermaciel** [comment]
I see three possible solutions to this.
1. The default configuration in `angular.json` is already set up so that `routes` is an empty array. We could change that to simply have `routes` set to "/".
- Problem here is if a user already adds the prerenderer but does not want to prerender "/" - e.g. they already have other routes they want to prerender - they could easily accidentally end up prerendering it because it is hidden in `angular.json`.
2. Change the builder so that if a user is not using the `RouterModule` we prerendering "/".
- The con to this approach is that users could be prerendering "/" using this default functionality and then add the `RouterModule` to their project later, at which point the prerender builder will be "breaking" for them - showing the `No routes found` error.
3. We leave things as is and expect users to specify their own routes to avoid making decisions about what routes to prerender on behalf of the user.
- Downside is a less easy developer experience.

@edbzn @alan-agius4 What are your thoughts?

**Comment by alan-agius4** [comment]
I am more inclined towards the second point, as it's also easy for the user to specify an empty array if they don't want to prerender the root page.

**Comment by edbzn** [comment]
Agree with @alan-agius4, I think it's the best option.

**Comment by alan-agius4** [comment]
Correction: I got confused with the bullet points and lack of indentation.

What I am inclined on is the following;
> The default configuration in angular.json is already set up so that routes is an empty array. We could change that to simply have routes set to "/".

Problem here is if a user already adds the prerenderer but does not want to prerender "/" - e.g. they already have other routes they want to prerender - they could easily accidentally end up prerendering it because it is hidden in angular.json.

Eventually, we can improve and iterate over it, especially if we see that it’s hard for a developer to get around this (I don’t think it will be the case). But I’d also go with this because it’s easier to support and maintain.
