### ISSUE TITLE
bundled dependencies include tokens for Express and Hapi

### ISSUE THREAD

**Issue by chrisguttandin** [angular/universal#1496]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [x] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8

### Description

Since v9 the @angular/cli seems to bundle dependencies by default for the server-side build. When that happens the bundle also contains the tokens for the express-engine and hapi-engine. That means the value for those tokens can't be provided from outside the bundle anymore since the tokens are not accessible anymore.

## 🔬 Minimal Reproduction

Create an Angular project with the following commands:

```
npx @angular/cli new demo
cd demo
ng generate universal --client-project demo
npm i @nguniversal/express-engine
```

Change the `src/app/app.component.ts` file:

```typescript
import { Component, Inject } from '@angular/core';
import { RESPONSE } from '@nguniversal/express-engine/tokens';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'demo';

  constructor(@Inject(RESPONSE) response: any) {
    response.status(200);
  }
}
```

Build the bundles:

```
ng build
ng run demo:server
```

Create a basic prerender script called `prerender.js` with the following content:

```js
require('zone.js/dist/zone-node');

const { promises: { readFile } } = require('fs');
const { RESPONSE } = require('@nguniversal/express-engine/tokens');
const { AppServerModule, renderModule } = require('./dist/demo/server/main.js');

readFile('dist/demo/browser/index.html', 'utf8')
    .then((document) => renderModule(AppServerModule, {
        document,
        extraProviders: [
            {
                provide: RESPONSE,
                useValue: { status () { } }
            }
        ],
        url: '/'
    }));
```

Run it:

```
node prerender.js
```

## 🔥 Exception or Error
<pre><code>
ERROR Error [NullInjectorError]: R3InjectorError(AppServerModule)[InjectionToken RESPONSE -> InjectionToken RESPONSE -> InjectionToken RESPONSE]: NullInjectorError: No provider for InjectionToken RESPONSE!
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.15.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

As a workaround I updated [angular-prerender](https://github.com/chrisguttandin/angular-prerender) to replace the require statements manually: https://github.com/chrisguttandin/angular-prerender/blob/master/src/functions/unbundle-tokens.ts

**Comment by alan-agius4** [comment]
Hi @chrisguttandin, most likely the problem is that the TOKEN used is not exported from the `main.js` bundle which caused DI to fail. Try to export the token from `main.ts` and used that in your server file. Similar to `renderModule`.

It's important to note that in Universal version 9. You don't need a script to prerender your server application as we now have a builder dedicated to do just that.

You can run prerendering by running the below npm script
```
npm run prerender
```

More info on version 9 features can be found: https://trilon.io/blog/angular-universal-v9-whats-new

Also from the steps above, it seems that you are not using the schematic to scaffold you universal application. To properly configure universal you need to use `ng add` instead of `npm i`

```
npx @angular/cli new demo
cd demo
ng generate universal --client-project demo
ng add @nguniversal/express-engine

```

**Comment by alan-agius4** [comment]
Hi @chrisguttandin, most likely the problem is that the TOKEN used is not exported from the `main.js` bundle which caused DI to fail. Try to export the token from `main.ts` and used that in your server file. Similar to `renderModule`.

It's important to note that in Universal version 9. You don't need a script to prerender your server application as we now have a builder dedicated to do just that.

You can run prerendering by running the below npm script
```
npm run prerender
```

More info on version 9 features can be found: https://trilon.io/blog/angular-universal-v9-whats-new

Also from the steps above, it seems that you are not using the schematic to scaffold you universal application. To properly configure universal you need to use `ng add` instead of `npm i`

```
npx @angular/cli new demo
cd demo
ng add @nguniversal/express-engine
```

**Comment by chrisguttandin** [comment]
Hi @alan-agius4, thanks for taking a look at this.

I'm aware of the new builder. I think it was inspired by angular-prerender. I created the custom `prerender.js` script only to demonstrate the problem.

As you said, the problem is that the "TOKEN used is not exported from the main.js bundle which caused DI to fail.".

If I use the prerender builder (`npm run prerender`) with the example app from above it fails because the builder doesn't inject the `REQUEST` and `RESPONSE` tokens.

If I use the `prerender.js` script it fails as well because the DI doesn't know that the provided `RESPONSE` token and the internally bundled `RESPONSE` token are the same.

I haven't tested it but I would expect the express-engine to fail as well since it uses similar code which also uses the tokens from outside the bundle. https://github.com/angular/universal/blob/master/modules/express-engine/src/main.ts#L76

It would of course be possible to export the tokens from the `main.server.ts` file but it would still not work with the express-engine and the prerender builder. That's why I created the issue.

I hope this makes sense. Please let me know if I'm missing something obvious.

**Comment by alan-agius4** [comment]
> If I use the prerender builder (npm run prerender) with the example app from above it fails because the builder doesn't inject the REQUEST and RESPONSE tokens. 

That is expected as unlike server side rendering during pre-rendering you don't have a Request nor Response since there is no no HTTP server. Pre-rendering happen during the build and for such case you should be using the `Optional` decorator from Angular core and mark `REQUEST` and `RESPONSE` as optional.

**Comment by chrisguttandin** [comment]
Yeah, I know that there is no actual request nor a response when prerendering an Angular App. However angular-prerender uses it to determine if a page should be rendered or not depending on it's status code. But this is just a side note and I can understand if you don't want to add this feature.

However the express-engine or hapi-engine are still affected by the problem that the bundle now contains the tokens as well since they use the unbundled tokens to provide the request and the response.

**Comment by alan-agius4** [comment]
> However the express-engine or hapi-engine are still affected by the problem that the bundle now contains the tokens as well since they use the unbundled tokens to provide the request and the response. 

The tokens need to be provided from the main bundle, if the server application is bundled, this was always the case and hasn't changed in version 9.

**Comment by chrisguttandin** [comment]
Ok, sorry for the confusion. I still don't know how this is supposed to work. I just stumbled upon the problem when I changed angular-prerender to work with v9.

If you don't think this is a bug feel free to close the issue.
