### ISSUE TITLE
use app-shell in angular universal is seo-friendly?

### ISSUE THREAD

**Issue by shomid** [angular/universal#1564]
I want to add app-shell to angular universal project but I'm afraid that's not good for SEO.
app-shell described in https://blog.angular-university.io/angular-app-shell/
use app-shell in angular universal is seo-fiendly?

**Comment by alan-agius4** [comment]
Hi @shomid, the only use case were app-shell is useful with universal is when having service workers or when not all the routes are server side rendered.

Otherwise there is no reason why app-shell should be used with universal, as the server side rendered snapshot will always override the app-shell snapshot making the latter redundant.
