### ISSUE TITLE
Angular app shell with Universal is not showing app shell

### ISSUE THREAD

**Issue by mvgadagi** [angular/universal#1574]
Hello Everyone,

I have enabled the Angular App Shell to my existing ( Angular Universal Project+ Angular Service Worker Enabled) by referring the guides from the official page https://angular.io/guide/app-shell.

The application shell not showing when I try to load the pages.

I am building the project with app  using 
`ng build --prod && ng run repro-app:app-shell:production`

And running the project using 
`node dist/repro-app/server/main.js`

I have added the reproduction repository here

https://github.com/mvgadagi/repro-app

I have run the Audit in the Chrome tab and it App Shell doesn't show hence First Contentful Paint is the same as without App Shell

![image](https://user-images.githubusercontent.com/3121238/78502540-44f9e080-777f-11ea-90bd-aafb39576737.png)

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mvgadagi** [comment]
Okay sure thanks a lot, let me create very fresh simple repo with v9.1

**Comment by mvgadagi** [comment]
@alan-agius4  I have added updated the descriptions with App Shell using my Reproduction Repo, Please take a look

**Comment by alan-agius4** [comment]
Hi @mvgadagi, thanks for the reproduction. 

Following the repro and updated description it is now clear what is your expected behaviour. 

The app-shell will **not** be displayed prior to the server side rendered page. SSR content will always override the app-shell, because you will have a single response from the server for a specific page and that will be the SSR'd page. From the server part, you can either have an app-shell or a server-side render page. You cannot have both.

With an SSR application the app-shell is only used when the a request is served from the service worker.
