### ISSUE TITLE
Angular 9 - How to prerender?

### ISSUE THREAD

**Issue by tzsveny** [angular/universal#1619]
I have an example project https://gitlab.com/tzsveny/test-prerender in which I wanted to test the new prerender option in angular 9.

But I don't know how to use it exactly. In my example project there is just one component for the root path which will generate & display a random number. If I use the new "prerender" script, it will create a new html in the dist folder with a number "X".

But when I do afterwards a npm run serve:ssr & test the root path with deactivated javascript, it will always show a new number "Y", which means it does not use the prerendered html file.

So does someone know, how to use the new prerender option correctly?

**Comment by wagnermaciel** [comment]
In order to serve the prerendered document from the default server provided using `npm run serve:ssr` you'll need to navigate to `http://localhost:4000/<ROUTE>/index.html`.

You can confirm that the page being loaded is prerendered by checking the elements tab in your browsers dev tools. A prerendered page will have a comment at the bottom marking it as a prerendered page.

In an ideal setup, the prerendered routes would be stored in a CDN which would automatically serve the prerendered files. Most CDNs are smart enough to serve files stored as `ROUTE/index.html` when users navigates to `/ROUTE`.

**Comment by CaerusKaru** [comment]
We're planning to do a docs revamp soon, and we'll include a section on how to use the prerender.

**Comment by alan-agius4** [comment]
The prerendering guide can be found at https://angular.io/guide/prerendering
