### ISSUE TITLE
Feature to avoid emitting references to the javascript

### ISSUE THREAD

**Issue by asgerjensen** [angular/universal#1721]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...
I am using SSR to serve up stripped html versions of the site to crawlers, and it works well. I am not using it to preboot the user experience.
Having added my api endpoints in robots.txt as Disallow, i noticed that google seemed to first get the generated HTML version, and then (for 20-30% of the pages), decided to start evaluating the javascript includes, thus restarting the app to crawl the page.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
A way to avoid emitting the   
```
<script src="runtime-es2015.ed9b4503676658b4387e.js" type="module"> 
etcetc
```
 part in the outgoing result, so the HTML was truely standalone.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Some kind of post-processing on the index.html to either break those links, or maybe add *.js to the robots.txt.

**Comment by CaerusKaru** [comment]
You can use the [`BEFORE_APP_SERIALIZED`](https://angular.io/api/platform-server/BEFORE_APP_SERIALIZED) provider for this. You would inject the `DOCUMENT` and then remove all script tags from the HTML that you don't want. This is the limit of support we'll provide on this issue, since it's not a bug or feature we feel the need to support. If you need more assistance, Gitter and StackOverflow are excellent forums for this.
