### ISSUE TITLE
Revamped Docs

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#1732]
This will be our tracking issue for rewriting/reviewing/handling the docs overhaul.

Current topics needed:
- [ ] how-to for prerendering (angular/angular#23024)
- [ ] preboot
- [ ] i18n
- [ ] socket-engine
- [ ] performance tips
- [ ] authN/Z
- [ ] cookies

**Comment by hiepxanh** [comment]
nice, that very good, but the changelogs is really hard to read. these Bot PR make me and other confuse to read it.

**Comment by KingDarBoja** [comment]
Awesome! 🚀 

A quick question, does these revamped docs gonna include the purpose of the `build:ssr` and `serve:ssr` commands? The [current guide](https://angular.io/guide/universal) only talk about `npm run dev:ssr` command.

**Comment by CaerusKaru** [comment]
@hiepxanh Changelog is being tracked in #1620 

@KingDarBoja Maybe, I'm not sure how useful that is. Those commands, if I recall, are mostly for users who don't want to use the Angular CLI builder, but instead want to run their own builds. `dev:ssr` runs the SSR dev server. Build and Serve are their own atomic functions.

**Comment by fazpu** [comment]
Hi, thank you, the docs is critical.

Every time I try to update Angular to current version, there is always a problem with Universal. I think it would be fair to at least point out the biggest changes made to the project setup.

I have to read about it on medium.com instead of the official (non-existent) documentation.

The example repo ([universal-starter](https://github.com/angular/universal-starter)) that used to be maintained was a source of clarity. Now it is archived.

I would prefer a bit buggy **well-documented** Universal rather than smooth running non-documented Universal, which I don't know how to install.

**Comment by MarcoGlauser** [comment]
Very nice to see that the docs get some updates.
I too think that more documentation around Angular Universal is crucial to get wider adoption.

We're currently evaluating Angular Universal against other ssr/prerender options and have no idea, what we're getting into with universal. (even with a working-ish prototype )
Since we're using a django backend, the socket engine might be interesting but there's just no information about it. From what I can tell, it was originally released alongside angular 6 but has not gotten a lot of love since?

Also, hints on performance improvements that go beyond the typical "don't use intervals or timeouts" would be awesome!

I'm very excited to see these changes land :)

**Comment by conradkirschner** [comment]
Added some documentation about the builders - still some tasks left, but better as "WIP" in the readme file maybe (?)

**Comment by CarlosTorrecillas** [comment]
Now that we are moving towards standalone components it would be very useful to have a version of the docs that illustrate how to configure Angular Universal using Angular 16 and standalone components

**Comment by alan-agius4** [comment]
Closing as this issue is not providing any meaningful context and since this was opened the docs have been improved. Regarding standalone there is a PR for this https://github.com/angular/angular/pull/51564.

For documentation related requests please open an issue in https://github.com/angular/angular/issues.
