### ISSUE TITLE
Separate the building of browser and server code in pre-rendering script

### ISSUE THREAD

**Issue by musso** [angular/universal#1736]
# 🚀 Feature request
Separate the building of browser and server code in pre-rendering script

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
Currently when running `ng run myApp:prerender`, it consists of building the server and browser code. When the server code is done, the build script will move on building browser code for each route.

In most CMS scenario, the code base is the same. Only the data in database or the deletion/additional of route are needed. It will be faster if there exists something like `ng run myApp:prerender --only route`, only building the routes from existing server code.

**Comment by CaerusKaru** [comment]
There's a `routes` option for the prerender builder. Is that what you're looking for?

**Comment by musso** [comment]
> There's a `routes` option for the prerender builder. Is that what you're looking for?

Skip the server build progress, just build the browser progress

**Comment by MarcoGlauser** [comment]
We have a use case that I believe is similar.

We want to prerender our public pages that change infrequently but are still managed by a cms for the ease of updating content.
We retrieve the content through an api call.
In a case of a content update, we need to recompile the whole angular application even though the code itself has not changed.
This means that it takes serveral minutes until the new prerendered page is online. The `routes` argument does not help in this case.

I know that  the express-engine exists, which handles dynamic content better but it is an overkill for us, since it adds a lot of complexity for data that only changes every few days or weeks. We're okay with blank pages for authenticated users.

It would be useful if routes could be prerendered without having to recompile the server and browser completely every time.
This would greatly reduce the time to deploy and make this solution more workable.

Splitting the route generation and compiling would be a good solution for us, because we could cache the intermediate compilation result.

Something along the lines of 
```bash
ng run project:prerender                          # compiles the server and browser target. this will be cached.
ng run project:prerender-routes --routes "/home"  # only compiles the browser target for certain routes.
```

**Comment by wagnermaciel** [comment]
### Context
When I was working on the design doc for this with Vikram we talked about adding an option like this but decided against it to avoid developers accidentally prerendering an outdated build. We were especially concerned with this happening if we ever coupled prerendering and ngdeploy - meaning a developer could accidentally _deploy_ the incorrectly generated pages.

### Implementation Details
If we look at [line 162 of prerender/index.ts](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/index.ts#L162), we can see that we use the output of the browser and server builds to locate a couple of files like the base index.html and the sever bundle. That's the only major complication I can see here. We'd still need to find a way to provide that information to the [_renderUniversal](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/index.ts#L104) method.

### Conclusion
If those concerns don't bother us enough, and if someone is willing to put in the work to figure out a neat solution for this, I think these changes are worth looking into. Especially because more than 90% of the time it takes to prerender comes from building the browser and server bundles.

**Comment by MarcoGlauser** [comment]
We ended up copying and adapting the [render.ts](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/render.ts) slightly. 

It prerenders 50+ routes within a couple of seconds, which makes content editing in the headless cms content and seeing the result after saving much more responsive. Which in turn creates less confusion.

**Comment by musso** [comment]
@MarcoGlauser  Can you explain it more?

**Comment by MarcoGlauser** [comment]
We adopted the file to this for Angular 10.1 
https://gist.github.com/MarcoGlauser/56d58a9d35f84d782e373d0fe522452b

The main difference is that we don't pass the html content of index.html as a parameter and instead read the contents of the file during the process. This  adds some overhead and might not work for some edge configurations but should work for most projects.

We transpile it during the build process. To do it manually, this should work
```
tsc prerender.ts
```

Once transpiled, we call it with node.
```
node prerender.js index.html dist/{myproject}/server/main.js dist/{myproject}/browser /route-to-prerender-1 /route-to-prerender-2
```

To run it concurrently, you can call it with a routes.txt file and xargs:
```
cat routes.txt | xargs --max-procs=4 node prerender.js index.html dist/{myproject}/server/main.js dist/{myproject}/browser
```

This process works well for us, but chances that it breaks with future Angular releases are very high.
Make sure you have the same version of the server and browser target, otherwise you're in trouble.

**Comment by webberig** [comment]
I have another use case for this feature.

Our website is built as a docker image. This image is being deployed in different environments where different api hosts are used. Since prerender must use the proper environment variables, it can only run when a container is spinning up  right before starting serve.

Since prerender is also doing another build, spinning up the kubernetes pod takes much longer.

**Comment by alan-agius4** [comment]
Closing as per https://github.com/angular/universal/issues/1736#issuecomment-674317641
