### ISSUE TITLE
document server router and http

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#176]
document how to include router and http for the server

**Comment by simb** [comment]
Did anything ever happen with this? I am trying to sort out how to get http wired in. My XMLHttpRequest is not available.  Not sure what the right path for getting http included in the universal is.  Or if that is even the right path.

**Comment by jeffwhelpley** [comment]
@simb check out this:

https://github.com/angular/universal/blob/master/modules/universal/server/src/platform/node.ts#L102

If you use the angular2-express-engine or angular2-hapi-engine, this part will be done for you, but if you are manually bootstrapping on the server, you will need to set the NodeXHRImpl yourself.

We are going to include this in the documentation for #258 so closing this issue.

**Comment by svallory** [comment]
@jeffwhelpley damn! Shame I didn't see your message before. Anyways... I am using angular2-express-engine and it wasn't working for me. So I created this: [angular2-http-node_backend](https://www.npmjs.com/package/angular2-http-node_backend)

**Comment by jeffwhelpley** [comment]
@svallory if you are using Universal, you are going to want to use the default http with the Universal NodeXHRImpl provider. The reason is that in Universal we count the number of times http is called during a given server side request. We need to do this because it is the only want to know how long to wait before sending back the response (i.e. if there are 4 http calls during a given server side request, we have to wait for all 4 to resolve plus one change detection cycle before sending back the response.

Let me know if you have any questions on this.

**Comment by svallory** [comment]
@jeffwhelpley Just checked the code on Universal. I see you guys are using xhr2 package so you get a `XmlHttpRequest` object on node. THAT is what I replaced by implementing `NodeBackend` and `NodeConnection` using native node APIs to perform the request. It's a lighter impl and, if you want, we could bring it inside universal and remove the dependancy.

I also see other problems:

1. Current impl of `NodeBackend` and `NodeConnection` [still uses `BrowserXHR`](https://github.com/angular/universal/blob/release-universal-0.50.0/modules/universal/server/src/http/server_http.ts#L138)

2. I couldn't find where NodeXhrImpl is actually used (or universal's XHR)

3. `NodeXhrImpl` calls `Http.get` (shouldn't it be the other way around?)

I'm still kind fresh on ng2 so bare with me if I got something wrong, ok?

**Comment by gdi2290** [comment]
@svallory can you make a PR to replace xhr2. `NodeXhrImpl ` is used for templateUrl etc here https://github.com/angular/universal/blob/10443e968c3afcff7610ef98f71c2abeb0a29473/modules/universal/server/src/platform/node.ts#L102

**Comment by svallory** [comment]
@gdi2290 I can. I'll work on it next weekend (it's carnival in Brazil :)). All I see in that file is `NodeXhrImpl` being imported and then exported inside a constant. I don't see it being used.

Since you mentioned templateUrl, currently relative URL's don't work. Is there a reason not to load it from FS when it's a relative URL?

**Comment by gdi2290** [comment]
comment in the other issue https://github.com/angular/universal/issues/264 as op issue is unrelated.
