### ISSUE TITLE
Indexing and crawling Issue 

### ISSUE THREAD

**Issue by Qasmi2** [angular/universal#1827]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

We are using Angular 9.0.0 (aka Angular Universal) in our website which serves dynamic content to our audience. 

We are not able to get our dynamic URLs (pointing to content pages) indexed at the Google Search Console (GSC) and also through our sitemap successfully accepted by GSC. Though GSC accepts, and indexes, static URLs but the crawler doesn’t even crawl them. 

One such example is the list of following pages 

https://www.youcan.tech 
https://www.youcan.tech/search 
https://www.youcan.tech/news 
https://www.youcan.tech/activities/All 
https://www.youcan.tech/activities/Music-and-Concerts 
https://www.youcan.tech/activities/Family-and-Kids 
https://www.youcan.tech/activities/Health-and-Fitness 

And the dynamic URLs give 404 messages, consider this url: https://www.youcan.tech/news-details/US-Tourist-Couple-Found/445760 as an example. 

Note: other URLs can be found through our GSC 

Please help us understand what and where we are making mistakes since our Angular implementation does show html of static pages, GSC accepts them but Googlebot doesn’t crawl them. Also, we would really appreciate it if you can suggest free/paid your own or market-based solution to the problem. We will readily use it.

We REALLY want your help in solving these issues ASAP as we have a shorter runway to revenue generation. Things are really hot here so help us survive and position to scale. 

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/Hi @Qasmi2, 

This forum is /blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That being said, taking a look at your application, you application will not be crawable by bots due to the lack of anchor tags `<a href="">`. If you disable JavaScript, the application is un-usable, you cannot navigate from one page to another and so crawlers.
