### ISSUE TITLE
Issues trying out the examples

### ISSUE THREAD

**Issue by 0xR** [angular/universal#196]
I really like this project and I want to try it out. However, I'm running into a couple of issues doing that.

1. there is no documentation on how to run the examples
2. `grulp serve` results in the error `Error: Cannot find module 'preboot'`. After  `npm i preboot` I get this error: `ReferenceError: window is not defined` at `somedir/angular-universal/node_modules/angular2/src/facade/browser.js:4:11`
3. `gulp test` gives me around a thousand errors like: `somedir/angular-universal/tsd_typings/node/node.d.ts(1573,9): error TS2300: Duplicate identifier 'ciphers'.`
4. there are 3 failing specs

The good news `gulp serve.preboot` does work and gives me a working demo. However the demo seems to be without angular2 serverside rendering, which is the reason I was looking at this project.

I am probably doing something wrong since there is no documentation for running the example. Could you add this documentation? A list of which commands to run would be very helpful.

**Comment by manekinekko** [comment]
Hi @0xR, fixing point [2] is on my list right now. 

We are also aware of point [3], see this issue https://github.com/angular/universal/issues/150. 
We are also working on a 5 min quick start documentation https://github.com/angular/universal/issues/169. We are also working hard to improve the developer experience, so please stay tuned.

**Comment by manekinekko** [comment]
Hi @0xR can you update your project and test again? @gdi2290 has fixed many issues. If you get TypeScript error `error TS2300: Duplicate identifier` just ignore them.

**Comment by gdi2290** [comment]
There are still type errors/warnings because we just have too many overlapping type definitions. If you want to get started with Universal Angular 2 you can check out the starter repo https://github.com/angular/universal-starter or contribute in the universal folder https://github.com/angular/universal/tree/master/modules/universal
I will close this issue but feel free to open another one or comment here for more questions
