### ISSUE TITLE
Handling "Cannot match any routes " in express engine

### ISSUE THREAD

**Issue by webberig** [angular/universal#2162]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [X] express-engine
- [ ] hapi-engine

### Is this a regression?

No

### Description

When an error occurs in the express engine, there seems to be no way to catch it and allow express to respond with a 500 error. Instead, the browser keeps waiting for a response that never comes.

A good example is provided by ticket #1630. If you navigate to a url that doesn't exist, the browser keeps waiting for a response that never comes. The server console shows an error, ie.:
```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'CCC'
Error: Cannot match any routes. URL Segment: 'CCC'
    at ApplyRedirects.noMatchError (/Users/mathieu/Projects/zimmo/v3-universal/dist/v3-universal/server/main.js:136824:16)
    at CatchSubscriber.selector (/Users/mathieu/Projects/zimmo/v3-universal/dist/v3-universal/server/main.js:136808:28)
```

While there is a specific solution for the given error in #1630, I'm looking for a more generic solution in case "something breaks" inside Angular. The end game is to not let the express app crash and/or return a 500 response to the browser.

I tried a few things to catch the given error in `server.ts`.

Example 1 - Generic Express error middleware:
```
  server.use(function (err, req, res, next) {
    // this is never called
    res.status(404).send("Sorry can't find that!")
  })
```

Example 2 - res.render callback
```
  server.get('*', (req, res) => {
    res.render('index.html', { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] }, function (err, html) {
        // this is never called
        if (err) { throw err; };
        res.send(html);
     });
  });
```

Example 3 - try/catch for `res.render`
```
  server.get('*', (req, res) => {
    try {
    res.render('index.html', { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
    } catch (err) {
       // this is never called
       throw err;
    }
  });
```

## 🔬 Minimal Reproduction

#1630 covers a straight-forward scenario.

## 🌍 Your Environment

<pre><code>
Angular CLI: 10.2.3
Node: 12.16.2
OS: darwin x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.3
@angular-devkit/build-angular   0.1002.3
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@angular/cli                    10.2.3
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Comment by webberig** [comment]
Today I did a new test with a new project. I tried crashing Angular by causing a NullInjectorError. I created an InjectionToken without providing it in the module and use `@Inject` in the app component.

Angular did behave as expected (blank page, NullInjectorError in console) and to my surprise the Universal did provide an error response (500).

My conclusion is that the problem isn't as bad as I feared, it does have some kind of error handling. Maybe it's just the " Cannot match any routes" error that's not being handled properly?

**Comment by lindsaylevine** [comment]
hello! i'm experiencing the exact same issue. like @webberig, i have tried error middleware, try catch, promise catching, res.render callback. no matter what, this error never gets caught, and causes the serverless function that wraps it to time out. 

<img width="717" alt="Screen Shot 2021-07-30 at 11 10 49 PM" src="https://user-images.githubusercontent.com/57350178/127726998-b226eb75-dd7c-4da6-a72d-1b7b272a8337.png">

i challenge [this comment](https://github.com/angular/universal/issues/1630#issuecomment-643715346) in the issue @webberig linked. this has been consistently reported across several angular repos. and as we've pointed out, try catch does not handle a res.render that never resolves or rejects because it is infinitely stuck. cc @CaerusKaru

related issues ive found:
1. https://github.com/angular/angular/issues/17073#issuecomment-316864447 -- this is an older one but seems very relevant to the underlying cause here. says fixed but the issue definitely still persists. 
2. https://github.com/angular/universal/issues/1810
3. https://github.com/angular/universal/issues/1425

**Comment by amakhrov** [comment]
Same here.
The issue is made more severe by the limitation of the Angular Router, which doesn't really allow to create a wildcard (fallback) route for arbitrary named outlets. (see https://github.com/angular/angular/issues/40845).
So requests like `/foo(bar:baz)` are never matched, and hang my server.

**Comment by webberig** [comment]
I've come to realise this is not really a Universal bug/problem. 

My mistake was to approach these errors from the Universal point-of-view, not realising they would prove problematic even without Universal. Even without Universal engine, Angular will behave odd when given examples in my previous posts occur.

Angular offers different options to handle errors, but does not implement them by default when you create a new application:
- Adding the fallback route (easiest solution for 404's)
- Provide your own ErrorHandler class (https://angular.io/api/core/ErrorHandler)
- Listen to NavigationError events (more advanced)

Developers should address given scenarios and add error handling to the Angular application. After that, Universal should land on its feet.

**Comment by amakhrov** [comment]
@webberig could you clarify how exactly we can intercept a routing issue like [this](https://github.com/angular/universal/issues/2162#issuecomment-969287175)?

> Adding the fallback route (easiest solution for 404's)

There seems to be no way to add a fallback to arbitrary secondary outlets

> Provide your own ErrorHandler

Error handler intercepts and logs this error. However, the app still remains in the hanging state, since the express route handler in Universal never resolves

> Listen to NavigationError events (more advanced)

Could you please clarify how it could be done to solve the problem?

**Comment by webberig** [comment]
@amakhrov 
> Error handler intercepts and logs this error

If you provide your own error handler, you can do what you want. Not just log the error.

```
@Injectable()
class MyErrorHandler implements ErrorHandler {
  constructor (private router: Router) { }
  handleError(error) {
    this.router.navigate(["/errorpage"], {
        skipLocationChange: true,
    });
  }
}

@NgModule({
  providers: [{provide: ErrorHandler, useClass: MyErrorHandler}]
})
class MyModule {}
```

If you want to use the router.events approach:

```
@Component({
    selector: 'mh-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    loading: boolean = true;

    constructor(private router: Router) {
        router.events.pipe(
        filter(routerEvent => routerEvent instanceof NavigationError)
    ).subscribe((routerEvent: Event) => {
            this.router.navigate(["/errorpage"], {
                skipLocationChange: true,
            });
        });
    }
}
```

These are just examples which may or may not work for your app. The key take-away is you need to add error handling to your Angular app, with or without universal. Angular offers different ways to do this, but fails to provide good advice on the matter in their guides and docs...
