### ISSUE TITLE
Compile time constants

### ISSUE THREAD

**Issue by klemenoslaj** [angular/universal#2525]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description

Sometimes it makes sense to run the code only on the server side, while on the client it is useless.

Such cases being:
- server side logging (don't want to pollute browser console)
- attaching global styles or scripts to head (yeah I know...)
- ...

### Describe the solution you'd like

It might make sense to provide a compile constant so developer can check if code is executed in the server or on the client.

**Comment by alan-agius4** [comment]
Isn't [isPlatformServer](https://angular.io/api/common/isPlatformServer) enough?

**Comment by klemenoslaj** [comment]
Can terser actually eliminate the code from the resulting bundle? What I'm trying to avoid is delivering huge chunks of JS to the client, while it only makes sense to be executed by the server.

**Comment by alan-agius4** [comment]
No, that will not cause dead code to be removed since `isPlatformServer` is a runtime thing, I think in general adding a build constant would cause users abuse this as it can be seen as an easy way out for bad architectural decisions. 

For example in one of your cases above, you mentioned that you want to use this constant to replace/remove a server logger. but in this case I'd consider this as an anti-pattern, where dependency injection should be used instead. Typically, you'd have different providers which are registered in the respective platform module and therefore server-only code are not included in the browser bundle and vice-versa. 

That said, I am interested to know more about your use-cases.

**Comment by klemenoslaj** [comment]
> For example in one of your cases above, you mentioned that you want to use this constant to replace/remove a server logger. but in this case I'd consider this as an anti-pattern, where dependency injection should be used instead. Typically, you'd have different providers which are registered in the respective platform module and therefore server-only code are not included in the browser bundle and vice-versa.

@alan-agius4 sure, that was a horrible example and what you say applies. DI could provide a real logger on the server and noop on the client.
However imagine the logging strings are large and prettified debugging information, which are never visible to the user, so I was thinking to get rid of said strings from the client bundle. With DI, strings are still there in the bundle, just not logged to the console.

Keep in mind that was just the first lame example that came to my mind 😬
If this never worked and Angular does not intend to add this, we can close this issue.

---

It is still possible to add compile constants by extending webpack config using custom builders tho, it's just not out of the box.

**Comment by alan-agius4** [comment]
There is a similar discussion going on in https://github.com/angular/angular-cli/issues/23738

Lets continue it there as it more appropriate since its build related feature.
