### ISSUE TITLE
preboot browserify dependency

### ISSUE THREAD

**Issue by thedark1337** [angular/universal#261]
Hi, I noticed as I was installing universal that in the preboot package browserify is being installed as a dependency. Is that needed or should that be a devDependency?

**Comment by gdi2290** [comment]
browserify is used for preboot

**Comment by jeffwhelpley** [comment]
Well, we can switch browserify to webpack or rollup, but it is a normal dependency, not a devDependency. The function of the server side implementation of preboot is to generate code and it needs one of those tools to help generate that code. If you split out the code generation to a separate library, it doesn't really buy you anything because it would still need to be a normal dependency.

**Comment by jeffwhelpley** [comment]
Closing this since we have #190 open to move off browserify.
