### ISSUE TITLE
Server crashes from evaluating functions executed after setTimeout

### ISSUE THREAD

**Issue by qdouble** [angular/universal#267]
Currently Universal will crash when parsing an unsupported function executed after setTimeOut, even though the function is not executed until after the page is fully loaded...for example...

```
setTimeout(() => {
            this.renderer.invokeElementMethod(this.myTag.nativeElement, 'focus', []);
 }, 100);
```

The above will cause "EXCEPTION: Error: not implemented". Methods called in setTimeout should either be ignored or better handled.

**Comment by gdi2290** [comment]
`'focus'` was not implemented for the server version of the DOM adaptor

**Comment by qdouble** [comment]
@gdi2290 yes, I understand that... the issue that was brought up in slack chat is more so that the server would not be executing that function anyway since it won't execute the setTimeout block until after the page has fully rendered, therefore the setTimeout block should be ignored or better handled.

**Comment by jeffwhelpley** [comment]
@gdi2290 this is interesting because some people want the body of setTimeout to be executed on the server. I think that we should likely make a hard, clear stance on async on the server. What do you think about making sure we wait on the server for both http and some new modules we create to wrap setTimeout (i.e. universalTimeout or whatever), but then all other setTimeouts are monkey patched on the server to do nothing.

Alternatively we can just tell people not to use setTimeout, but that may just lead to inevitable issues.

**Comment by gdi2290** [comment]
@qdouble we’re tracking `setTimeout`, `setInterval` (although no one should use this for SSR), and `setImmediate` now in zone.js with angular2-universal-polyfills `0.3.1` and our new way of checking when the app is stable via `checkStable`
