### ISSUE TITLE
Create Universal Storage module

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#272]
we should allow users to use localStorage both in server/client

**Comment by gjuchault** [comment]
@gdi2290 Would this storage be shared with the client (same keys/values) ? Or would it be just a "polyfill" ?

**Comment by zcoon** [comment]
@gdi2290 as this has been taken off of the Beta.0 milestone, do you have a vision for when angular universal will offer localStorage support? Thank you in advance

**Comment by gdi2290** [comment]
I'm introducing a Universal Cache service that will be used in localStorage after the initial rc6 release

**Comment by cyrilletuzi** [comment]
@gdi2290 For now localStorage is not accepted in my Universal app (everything else is working) and crashes the server, is there something special to import or is it not ready yet ?

**Comment by gdi2290** [comment]
@cyrilletuzi to transfer state from the server to the client you can use a lifecycle hook in Node and the helper flags `isBrowser` and `isNode`
```typescript
import { isBrowser, isNode } from 'angular2-universal';

@NgModule({
  bootstrap: [ App ],
  declarations: [ App, Home ],
  imports: [
    UniversalModule, // BrowserModule, HttpModule, and JsonpModule are included
    FormsModule,
    RouterModule.forRoot([
      { path: '', component: Home, pathMatch: 'full' }
    ])
  ]
})
export class MainModule {
  constructor(public appRef: ApplicationRef) {
    // lives in your browser main module
    if (isBrowser) {
      if (UNIVERSAL_CACHE[key]) {
        localStorage[key] = UNIVERSAL_CACHE[key]
      }
    }
  }
  // lives in your node main module
  universalDoDehydrate(universalCache) {
    var yourServiceWithState = this.appRef.injector.get(YourServiceWithState)
    var key = 'yourServiceWithState._state'
    universalCache[key] = yourServiceWithState._state.justOneProp
  }
}
```

**Comment by cyrilletuzi** [comment]
@gdi2290 thanks!

**Comment by gdi2290** [comment]
after I create universal lifecycle hooks for the client then this will be more seamless

**Comment by joshmattvander** [comment]
@gdi2290 where does UNIVERSAL_CACHE come from? I am running `^2.0.11`

**Comment by gdi2290** [comment]
it's created by universal on the server and sent to the client

**Comment by CL0SeY** [comment]
@joshmattvander @gdi2290 
I had to use this (with typescript):
```
let UNIVERSAL_CACHE = window['UNIVERSAL_CACHE'];
if (UNIVERSAL_CACHE[key]) {
  // do things with the cache
}
```
Is there a nicer way to access the cache?

**Comment by gdi2290** [comment]
there needs to be a `universalDoRehydrate` lifecycle method that is not there yet so for now using `UNIVERSAL_CACHE` in the way you describe works for now until I get more time to prioritize it

**Comment by wellingWilliam** [comment]
Is there a way to transfer state from client to server?

**Comment by PascalPrecht** [comment]
@wellingWilliam This is what @gdi2290 described in the comments above

**Comment by wellingWilliam** [comment]
@PascalPrecht are you sure? I know universal cache can transfer state from server to client, but can it also be used to transfer state from client to server. Such as, client fetches a token and uses it to login to get a user payload. How can the server be aware of the token to prerender with the user payload?

**Comment by gdi2290** [comment]
to transfer state fro, client to server you can simply make an http call

**Comment by wellingWilliam** [comment]
I was thinking that, but how to scope the http call to the node for the client making the request? I assume the server would need an endpoint for the request but what would it do?

**Comment by wellingWilliam** [comment]
If the client transfers state by a http request after preboot and the server stores the state, when the client refreshes the page how can the server know which stored state belongs to the new request to prerender with the state?

**Comment by MarkPieszak** [comment]
It sounds like you need some initial logic the moment before the app gets serialized, or during, so that it can decide what route to instead render, or components to show,etc ?

What are you trying now?

**Comment by wwelling** [comment]
I have trashed all attempts thus far. 

Here is the project I would like to implement this is in: 
[Prometheu Universal](https://github.com/wellingWilliam/prometheus-universal)

For the following use cases assume that a user navigates to the app and it bootstraps the universal app on the client side. The user then logs in, which receives a token and is placed in localStorage and Universal Cache. The token is then used to request the user payload. At this time the server is unaware of the token and must be transferred via an http request, as specified by @gdi2290.

Use cases:
1. page refresh
2. user navigates away and back
3. remember me log in and favorite link for quick navigation

I am able to send the token to the node server and store it in a map or a redis server. The problem is what key would I use to store it and how would a new request know what key to use to fetch the token.

**Comment by wwelling** [comment]
Is server client synchronization going to be a consideration for the Universal Storage module?

**Comment by wellingWilliam** [comment]
I will setup a fresh clone of universal starter and modify to demonstrate the problem. 

I have no idea on how to allow pre-rendering with state set on client side after bootstrapping without digging into angular universal code. Universal cache is one way, server to client. Universal storage sounds like the name of the feature that should support this functionality. 

I also discovered another use case for this. When using a CanActivate interface to protect routes based on authentication. Assume a user has logged in and stored its state in session or local storage. They then navigate away from the app and back. They will still be logged in by retrieving the state from storage on the client. But the CanActivate guard will check their authentication on the server and not activate the component.

**Comment by wwelling** [comment]
https://github.com/angular/universal-starter/pull/308

This demonstrates the issues from a lack of synchronization between client and server after bootstrapping. I will continue with trying to make a request to the server to store the token on the server in which a request can fetch it in order to pre-render with the user. I am thinking the request is going to have to have a cookie that identifies the state stored on the server.

**Comment by wwelling** [comment]
Ok, I have it to where the token is synchronized and state is pre-rendered correctly. However, the token is stored on the server without any unique identifier for retrieval upon new request. Now the true nature of the problem. How to map a given request from the client to retrieve a stored state on the server in order to pre-render the appropriate state. I am guessing a cookie.

**Comment by wwelling** [comment]
A cookie worked well. Although it seems strange implementing Universal Storage using a cookie to identify the client state on the server. Anyhow, I am happy with the solution. I hope that there is a seamless solution in Angular Universal in the future that does not require a bunch of custom code to support this functionality.

**Comment by wwelling** [comment]
This approach is insecure for handling authentication tokens. I am going to close the pull request to universal starter because it does not fall under the description of minimal Angular 2 starter. Here is the branch repo I've been working on with client to server state transition.

https://github.com/wwelling/universal-starter/tree/fake-token-login

**Comment by MarkPieszak** [comment]
@wwelling Which file were you trying to do it, let me take a look so I can see what you need.

**Comment by wwelling** [comment]
client to server transfer:
https://github.com/wwelling/universal-starter/blob/fake-token-login/src/%2Bapp/shared/storage.browser.ts

backend store:
https://github.com/wwelling/universal-starter/blob/fake-token-login/src/backend/store.ts

node.module.ts
```this.cache.set('APP_ID', universalCache.APP_ID);```

set token in store:
https://github.com/wwelling/universal-starter/blob/fake-token-login/src/%2Bapp/%2Blogin/login.component.ts

get cookie before bootstraping:
https://github.com/wwelling/universal-starter/blob/fake-token-login/src/%2Bapp/shared/cookie.node.ts

It is very scattered. I admit this is a mess. Honestly, I don't see how this can be accomplished securely with auth tokens. A server should never hand out auth tokens without being provided credentials. As for non secure state it would still not be a good approach due to poor synchronization.

**Comment by wwelling** [comment]
I apologize for wasting your time on this.

**Comment by MarkPieszak** [comment]
Is everything working or are you worried about security with this? No worries! Sorry if I'm slow to respond, I've been trying to tackle of a few things at once, it's hard to find time for everything :)

**Comment by wwelling** [comment]
Thank you for the response. It works but is insecure and not practical. I was taking the wrong approach to provide a token to the server for pre-rendering. A cookie is the correct approach. Is easily acquired in the node module from the Zone request. Although, there will still be no synchronization between server and client local storage as of yet.

**Comment by gdi2290** [comment]
won't be supported officially 
https://github.com/angular/angular/issues/13822

**Comment by vforv** [comment]
This solution not working for me @gdi2290  could you help:

http://stackoverflow.com/questions/43350949/how-to-store-token-on-server-side-angular-universal

**Comment by fulls1z3** [comment]
I made it :)

Have a look at [universal-example-app](https://github.com/nglibs/universal-example-app) for its usage.

Quoted from https://github.com/nglibs/universal-example-app/issues/5

> Check the implementation: just updated this repo as well as publishing 5 separate packages for cache operations both on server and browser platforms. Everything is handled via the `@Cached(...)` decorator on the method/loader/etc which you want it cached. Also, there's the possibility to use caching methods (`has`, `get`, `set`) using the caching API.
> 
> - [ngx-cache/core](http://github.com/ngx-cache/core): cache utility
> - [ngx-cache/platform-browser](http://github.com/ngx-cache/platform-browser): browser platform implementation
> - [ngx-cache/platform-server](http://github.com/ngx-cache/platform-server): server platform implementation
> - [ngx-storage/core](http://github.com/ngx-storage/core): storage utility (required for server platform)
> - [ngx-storage/fs](http://github.com/ngx-storage/fs): fs implementation (required for storage core)
> 
> You might ask why to keep the structure so complex and consume 5 different package? The answer is, not all the use cases depend on caching on the server platform. Furthermore, this structure allows to integrate any kind of custom caching with the server or browser platform (*ex: session, api, etc*).
> 
> Currently there's no documentation available for these packages, because these days I'm kinda overloaded with many different tasks/projects. I think in a week or two I'll try to provide a good documentation as well as unit tests for these packages.
> 
> However, try to have a look on this repo - about the use of `CacheService` and its instruments. I think it won't be difficult to understand the concepts, as I've kept the code style as DRY as possible.
