### ISSUE TITLE
Optional route params with pre-rendered views

### ISSUE THREAD

**Issue by zanettin** [angular/universal#275]
Related to this issue => https://github.com/angular/router/issues/397 I'm not sure if this an issue or a missconfig from my side. Do I need to specify the route on the node side specialy or is it a bug from the router itself?

issue assigned to: @alexpods

**Comment by gdi2290** [comment]
We created our own version of Location Platform so this could really be our fault with the way we're managing the location

**Comment by zanettin** [comment]
Thanks for your fast reply. I'll close the other issue on angular/router.

**Comment by gdi2290** [comment]
@alexpods will take this issue

**Comment by alexpods** [comment]
@zanettin @gdi2290 The bug is in core router library. More precisely it's [here](https://github.com/angular/angular/blob/master/modules/angular2/src/router/instruction.ts#L162). As you see `urlParams` are used only in `_stringifyMatrixParams()` which is called only if we have `auxInstructions` (see [here](https://github.com/angular/angular/blob/master/modules/angular2/src/router/instruction.ts#L198)). So if we don't have auxilary routes then `urlParams` will never be used.

@zanettin Could you open the issue in core angular2 repository?

**Comment by zanettin** [comment]
thanks for your time @alexpods! i've re-opened the issue on the core router repo.

**Comment by alexpods** [comment]
@zanettin I've also opened the issue in the core repository https://github.com/angular/angular/issues/7367. I think the core team will be more active to close the issue there (at least I hope so).

**Comment by ganeshkbhat** [comment]
Raised similar issue https://github.com/angular/router/issues/397 >> http://stackoverflow.com/questions/35691663/child-url-query-params-shown-with-instead-of/35698213

**Comment by alexpods** [comment]
@ganeshkbhat It's matrix URL https://www.w3.org/DesignIssues/MatrixURIs.html

**Comment by ganeshkbhat** [comment]
Thank you... my bad.
