### ISSUE TITLE
[Happens 2% of the time]: Perpetual loader when using serve-ssr

### ISSUE THREAD

**Issue by CharlieGreenman** [angular/universal#2962]
Page will continue to show loader even once page has loaded when using angular ssr. (screenshot attached) 

![Screen Shot 2022-12-31 at 8 25 33 PM](https://user-images.githubusercontent.com/8540141/210152562-b7417b0f-db1d-49a5-a433-d98dee5da443.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular//universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by CharlieGreenman** [comment]
You know there's a fine line between us the users having the time and reporting an issue as well. This approach is not it. Ask me to re-update the issue. Don't close it please. Please reopen this issue and allow me to update it. Thank you

**Comment by alan-agius4** [comment]
Hi,

I am sorry you feel this way but it is also not okay to delete the issue template. In this case given that this issue does not have any of the required information. It's best to open a new issue so that all the information required in the template is provided and avoid additional unnecessary back and forth.

Thank you for your understanding.
