### ISSUE TITLE
preboot with multiple appRoot

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#303]
with more than one appRoot on the page we need to attach the `preboot.init()` after each `appRoot`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Universal Angular 2</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="data:;base64,iVBORw0KGgo=">
  <base href="/">
</head>
<body>

  <app>
    Loading...
  </app>

  <my-app>
    Loading...
  </my-app>

</body>
</html>
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Universal Angular 2</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="data:;base64,iVBORw0KGgo=">
  <base href="/">
</head>
<body>

  <script>// preboot source</script>
  <app>
    Loading...
  </app>
  <script>preboot.init({ appRoot: 'app' })</script>
  <my-app>
    Loading...
  </my-app>
  <script>preboot.init({ appRoot: 'my-app' })</script>

</body>
</html>
```
currently hardcoded to the first one

**Comment by jeffwhelpley** [comment]
This is what will need to change for this:

1. Change preboot_options.ts PrebootOptions interface so that appRoot accepts either a string or an array of strings.
2. Change dom.ts:
  * Instead of appRoot, serverRoot, clientRoot, the state should have a `roots` value that is an object which maps the root selector to an object that contains app, server and client values
  * Change other dom functions so it works with the new roots object
3. Modify preboot_browser.ts so that:
  * in load() we have to get each of the nodes and then save them in dom.updateRoots()
  * for complete() for NOW we are just going to implement calling this once when all apps are complete. In the future we will make another change so we can call this for each app individually. So, you would loop through the roots and replay, buffer switch, etc. for each one.
4. Update buffer_manager.ts so it works with multiple roots under preboot.dom.state.

Other than that, there may be some references to roots that I missed which we need to address. John, ping me if you have any questions on this.

**Comment by gdi2290** [comment]
`.complete()` should be called for each root so maybe `.complete('my-app')` we should also provide a way to check if the component even needs preboot (if they don't have any inputs because it's just static)

**Comment by jeffwhelpley** [comment]
So, one thing at a time. Let's definitely not include the check to see if component needs preboot thing. This change is already complex enough.

As for the `.complete('my-app')`, the way that would be implemented is that we will need to group the events in the event_manager by the different app roots. 

@JohnGorter let me know if you have any questions on this.

**Comment by JohnGorter** [comment]
Instead of appRoot, serverRoot, clientRoot, the state should have a roots value that is an object which maps the root selector to an object that contains app, server and client values
Change other dom functions so it works with the new roots object??

do you mean someting like this:

 state.roots = state.roots || {
      rootselector: string = "app",
      appRoot = state.body,
      serverRoot = state.body,
      clientRoot = state.body; 
  };

Should the roots not be an array?

**Comment by jeffwhelpley** [comment]
There are two approaches. We change preboot to be class-based and focus on one app and then create an instance of it for each app OR we change the internal structure to manage multiple roots. We are going with the latter since we can almost certainly create some efficiencies in terms of code size and performance. So, the starting point with this is how we store the roots themselves (as you have listed). I think it makes sense to make the roots and object that maps the app root selector string to an object that contains the actual root values. Something like this:

```
state.roots = state.roots || {};
state.roots['app'] = {
  serverRoot: state.body,
  clientRoot: state.body
}
```

All the rest of the code updates would then basically be changing each function to accomidate this new structure. As an approach, I would suggest starting with the furthest downstream dependency (which I believe is dom.ts) and then work your way up. You can update the corresponding unit test with each file as you go. Let me know if that makes sense.

**Comment by gdi2290** [comment]
done with preboot 4 presumably
