### ISSUE TITLE
add github templates

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#319]
update the repo to use github templates. (for context https://github.com/blog/2111-issue-and-pull-request-templates) examples are in the angular2 repo

**Comment by manekinekko** [comment]
@gdi2290 are these templates OK?

### Issue

**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender


* **Do you want to request a *feature* or report a *bug*?**



* **What is the current behavior?**



* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.



* **What is the expected behavior?**



* **What is the motivation / use case for changing the behavior?**



* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]



* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)


### Pull Request

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
remove unused proxy imports from some test files


* **What is the current behavior?** (You can also link to an open issue here)



* **What is the new behavior (if this is a feature change)?**



* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No


* **Other information**:

**Comment by gdi2290** [comment]
LGTM

**Comment by manekinekko** [comment]
great. I'll send the PR

**Comment by gdi2290** [comment]
merged via https://github.com/angular/universal/commit/707580dc28b59a49fc7baee53b5c56673f76a65a
