### ISSUE TITLE
preboot cannot find client nodes to replay events

### ISSUE THREAD

**Issue by taylorstine** [angular/universal#333]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ x] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
When I try to preboot, I get a message saying that all of the events I performed could not be replayed, because the client node could not be found (note that I am using the `debug` option).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
1. Enable preboot (my render call looks like this)

```

res.render('index', {
        directives: [Html],
        providers: [
          provide(APP_BASE_HREF, {useValue: baseUrl}),
          provide(REQUEST_URL, {useValue: url}),
          ROUTER_PROVIDERS,
          NODE_LOCATION_PROVIDERS,
          NODE_PRELOAD_CACHE_HTTP_PROVIDERS
        ],
        async: false,
        preboot: {
          uglify: false,
          appRoot: 'root',
          debug: true
        },
      })
```
2. Throttle the network speed so that you have time to do some events that should be replayed.  In my case I have an input field I type in to 
```
<input id="inputField" preboot-events="keypress,focus" [(ngModel)]="hero.name" placeholder="name">
```

3. Observe that once the client script loads, you see messages saying the events could not be replayed, and indeed the events are not replayed.
* **What is the expected behavior?**
The events are replayed

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.12
- Browser: [Chrome 49]
- Language: [TypeScript 1.8]
- OS:  [Mac OS X]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

[In this line](https://github.com/angular/universal/blob/master/modules/preboot/src/browser/buffer_manager.ts#L22), why do we want to make a deep copy?  Since this isn't a deep copy, [when we try to find the node in the client root on which to replay the events](https://github.com/angular/universal/blob/master/modules/preboot/src/browser/replay/replay_after_rerender.ts#L21), we get null (which makes sense because the client root was copied without any children).

Shouldn't we make a deep copy? Or in [this line](https://github.com/angular/universal/blob/master/modules/preboot/src/browser/buffer_manager.ts#L31) pass `(serverRoot, serverRoot, serverRoot)`

**Comment by taylorstine** [comment]
Note that setting `buffer: false`, fixes this problem, but I'm still curious about how to make this work with the buffer.

**Comment by jeffwhelpley** [comment]
@taylorstine I am in the process of making a number of fixes, so I will have something for this within a couple days.

**Comment by jeffwhelpley** [comment]
@taylorstine OK, so I am in the process of submitting my PR today, but to clarify a couple things:

1. We make a shallow copy because we just need the root div where Angular will render to on the browser side. So, all the nodes will be there as soon as Angular is done rendering.
1. In your preboot config you forgot to include `listen: 'attributes'` which is needed if you are identifying preboot events through the `preboot-events` attribute on an element.
1. When you do this, though, it still won't work until you also add `replay: 'rerender'` to the preboot options. In my PR I am adding `rerender` as the default so you won't need to explicitly specify it moving forward.
1. In general, I would strongly suggest either using the `presets` option or specifying your own listen by selectors options rather than listen by attributes. I know there is no documentation on this to guide you yet, but you should check out the [presets code](https://github.com/angular/universal/blob/master/modules/preboot/src/node/presets.ts) to get a feel for how it works and let me know if you have any questions.

So, you should be able to get this working on your own with my suggestions, but my PR will make it slightly easier since I will have some default settings to protect you.

**Comment by taylorstine** [comment]
@jeffwhelpley :1: thank you very much.  I've implemented your suggestions, and everything is working like a charm :four_leaf_clover:

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/commit/389238ba8c834a46b4d420696d142802783f6111
