### ISSUE TITLE
The build process is broken.

### ISSUE THREAD

**Issue by manekinekko** [angular/universal#41]
There are few issues with the build process. I just npm install and ... BOOOUM! 

see screenshot below...
![image](https://cloud.githubusercontent.com/assets/1699357/9050716/725f1164-3a51-11e5-9ec7-e99c0dd05b6f.png)

**Comment by gdi2290** [comment]
the first error has to do with typescript.
https://github.com/angular/universal/blob/master/package.json#L75

the second one is a problem trying to copy the built files from angular submodule build.
https://github.com/angular/universal/blob/master/scripts/update-ng-bundle.sh

the third is a problem with protractor including webdriver which I have to look into `webdriver-manager update --standalone`

This also could be a problem with the installation. Can you try running this command `npm run clean && npm start` and see if you have the same errors?

**Comment by gdi2290** [comment]
I think I'll update `update-ng-bundle.sh` to copy the angular dist over which seems like a better aprouch than manually updating the script inside package.json

**Comment by manekinekko** [comment]
Issue 1 and 3 were related to my installation which was broken (the last npm install wasn't ok).
However, issue 2 is related to a missing folder  `/angular/dist/bundle/` which was moved to `/angular/dist/js/bundle/`

**Comment by manekinekko** [comment]
after updating `update-ng-bundle.sh` (https://github.com/angular/universal/blob/master/scripts/update-ng-bundle.sh#L7) everything is OK.

**Comment by gdi2290** [comment]
this wasn't the first time `update-ng-bundle.sh` broke due to the file paths being hard coded. The gulpfile configuration isn't being exported in the angular repo so I can't grab the files. At the moment I'll just rely on the `dist/` folder being created

**Comment by manekinekko** [comment]
I see. May be you could just symlink the angular2/dist folder to web_modules? Or use angular2/dist directly?!
What is the need of web_modules?

**Comment by gdi2290** [comment]
`web_modules/` was reserved for static file usually meant for the client. Previously this included `reflect-metadata`, `traceur-runtime`, `system.js` and at first the files were git committed into the repo. There was a problem with initial load times using the `system.js` 0.16.x that lead to having to download the latest updates for each one. Then the installation time slowed down due to downloading these files all the time. That lead to a refactor of either recreate features that bower does already for managing static files or just use bower. Sadly we don't have the same luxury for nightly builds in bower as we did for ng1. Now we only manage the static files generated from angular only to ensure the API remains the same when rendering the app on server/client. There could be a breaking change in master that's not reflected on npm (released versions).

ultimately the answer is to remain on npm releases rather than master releases which would speed up install/build

**Comment by gdi2290** [comment]
symlink doesn't work on windows or something but that would be solved by expanding gulp tasks https://github.com/angular/universal/issues/42

**Comment by manekinekko** [comment]
Yeah! I think moving to gulp would solve many issues. I will check if I have some time tomorrow to take care of #42 

Now I need to go take a nap, it is 4am here in Paris, and I have work at 9am :smile:

**Comment by gdi2290** [comment]
kool, yeah no rush. Thanks for your help

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/pull/58
