### ISSUE TITLE
express-engine renders only first visited route if template doesn't change

### ISSUE THREAD

**Issue by ianbelcher** [angular/universal#421]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**

- [x] express-engine

* **Do you want to request a *feature* or report a *bug*?**

Bug in commit 73ea470c380c5a82baebd37975edd4c36847ebbe

* **What is the current behavior?**

The above commit has introduced a bug where a new template must be passed to express-engine for the providers to be reloaded. From my experience, most ng2 apps are using a single core html template which means that changing the template very rarely happens.

The issue here is that regardless of the the provided REQUEST_URL, the template engine will always render the initially passed value, breaking any app that uses routes. (Related to https://github.com/angular/universal-starter/issues/79#issuecomment-220157945 and maybe https://github.com/angular/universal-starter/issues/90 and maybe https://github.com/angular/universal/issues/379)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

An clone and install of the ng2 starter project will produce this behaviour.

* **What is the expected behavior?**

We want the express-engine to render the correct route.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://github.com/angular/universal/commit/73ea470c380c5a82baebd37975edd4c36847ebbe#diff-9931604be9f9e940c9accd8abc6b0926L69 is where the previous logic existed to overwrite the given providers based on the `reuseProviders` option.

I'm quite happy to put together a PR for this issue, but need to know whether the removal of the `reuseProviders` option is because it is planned for removal from the `ExpressEngineExtraOptions` interface, or whether this was an oversight. Currently this option only exists in the interface and is not being used elsewhere from what I understand.

**Comment by visikov** [comment]
@ianbelcher I was able to get routing to work by adding

`!!_options.reuseProviders === false ||`

to: https://github.com/angular/universal/blob/master/modules/express-engine/src/engine.ts#L74

then passing `reuseProviders: false` into the config param.

Should I make a PR for this or do you have a better solution in mind?

**Comment by ianbelcher** [comment]
@visikov That fix will definitely work, but I'm unsure as to how performant it will be to continually dispose of and rebuild the bootloader for every request when we should only be overwriting the providers based on the `reuseProviders` option. It's likely better to seperate the building of the `EXPRESS_PLATFORM` and the `EXPRESS_ANGULAR_APP` objects into different sections based on the options which have been passed in and try and reuse as much instantiated code as possible? Again, I'm not fully across how the Bootloader class works and I might be making some bad assumptions as this class does get the injected with the providers (through the `_options` argument) when its constructed.

For now, I've got my project working by moving lines 87-89 (https://github.com/angular/universal/commit/73ea470c380c5a82baebd37975edd4c36847ebbe#diff-9931604be9f9e940c9accd8abc6b0926R87) outside of the `EXPRESS_ANGULAR_APP.template !== _template` logic so that its set each request.

@gdi2290 Did you have any guidance as to what might be the best course of action here?

**Comment by visikov** [comment]
@ianbelcher You're probably right about re-instantiating the bootloader on every request.

I've amended my PR based on your suggestion. Although I'm still a little iffy about it. Shouldn't the rendered page always reflect the state of the page? Having to pass in `reuseProviders: true` defeats the purpose imo.

I'll leave the PR open for now, hopefully someone who has a more intimate knowledge of this project will chime in.

**Comment by ianbelcher** [comment]
Your right about the iffiness of it, this section feels like its still in quite a bit of flux as is the whole ng2 ecosystem. Things are moving very quickly!

That was my thoughts as well regarding the fix. I feel PatrickJS will have a much better idea for where things are going in this case. It appears that we want to change only certain providers per request while caching the others?

**Comment by gdi2290** [comment]
providers and directives should be moved outside of the if statement.
https://github.com/angular/universal/blob/master/modules/express-engine/src/engine.ts#L87...L#88

`reuseProviders` should really be renamed to `reuseAppProviders` but really should be removed now with the recent changes in `rc.1`. 

In angular 2 we have 3 main injectors.
1. platform injector -> `platformProviders`
2. application injectors `providers` aka applicationProviders aka appProviders
3. component injectors

In an ideal world, we would only need to recreate the component injectors while reusing the platform/application injectors. Here are a few scenarios that we need to work with.

* you may have more than one app per route.
checking if the template is different determines that we should create another bootloader

* we can't determine that the developer is not maintaining state within services in the application providers
`reuseProviders` would provide the same list of providers reference rather than the new one during this request/response

* we need to change the interface yet again if the developer wants to have different appInjectors for each root component.
right now the same app providers are used for each root component. this isn't a big issue since it's mostly used for pre-rendering during the build step

* you may only have one bootloader at a time
angular 2 maintains a reference after the platform is created which we don't want on the server since we want to manage it. There is a way to set/remove of this reference which we may end up using

**Comment by gdi2290** [comment]
this is fixed in version `0.101.5` just released
