### ISSUE TITLE
new new router support

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#453]

**Comment by gdi2290** [comment]
it already works without any changes so long as `NODE_LOCATION_PROVIDERS` is included

**Comment by maissani** [comment]
node_modules\angular2-universal\package.json:
   74      "@angular/platform-browser-dynamic": "2.0.0-rc.1",
   75      "@angular/platform-server": "2.0.0-rc.1",
   76:     "@angular/router-deprecated": "2.0.0-rc.1",
   77      "angular2-express-engine": "file:../express-engine",
   78      "angular2-hapi-engine": "file:../hapi-engine",

node_modules\angular2-universal\src\browser\router.ts:
    1: import {ROUTER_PROVIDERS} from '@angular/router-deprecated';
    2  
    3  export const BROWSER_ROUTER_PROVIDERS = ROUTER_PROVIDERS;

.....
node_modules\angular2-universal\src\node\render.ts:
   27  import {NgZone, ComponentRef, Provider, Type} from '@angular/core';
   28  import {Http} from '@angular/http';
   29: import {Router} from '@angular/router-deprecated';
.....


Are you sure that no changes is required. 
In some apps, we have to rename router-deprecated to router because it works with any changes ;).

**Comment by maissani** [comment]
Cleanup NG2 universal please.

**Comment by MarkPieszak** [comment]
What needs to be cleaned up @maissani, I can take a look. 
Do you mean the examples? I do think you're right those need a little cleanup now.

Also yes, of course `@RouteConfig` has to be changed to `@Route`, imports have to be changed, you need to npm install the latest v3-alpha router etc.

I believe Patrick meant that Universal *itself* didn't require any under the hood changes, it just requires `NODE_LOCATION_PROVIDERS` to be passed in. 
 
If you check out the Starter repo - he updated it recently to showcase everything. https://github.com/angular/universal-starter

**Comment by maissani** [comment]
I mean the modules are not fully updated and it still remains some delcarations that in some case break the Angular2 Universal with the new router.
### In my opinion : NG2 Universal is put to Instable State for the moment.

**Comment by gdi2290** [comment]
The breaking change is that I removed `BROWSER_ROUTER_PROVIDERS` which was depending on the old router. Where you found the old router in hapi-engine and express-engine was not meant for anyone to use outside of this repo. The package.json deps in the root of this repo doesn't matter or affect any of the modules and really should be removed. The biggest mistake was BROWSER_ROUTER_PROVIDERS where I didn't plan on 3 routes happening. It's only meant to be a helper to show what's happening but is unnecessary. 

The version that is going forward without the old router is `0.104.1` while `0.103.3` still depends on the old router.

**Comment by maissani** [comment]
> Where you found the old router in hapi-engine and express-engine was not meant for anyone to use outside of this repo.
Can you explain me why did it exist an npm repo of those modules that pointing on universal package if they are not intended for being used outside of this repo ? 
Example : https://www.npmjs.com/package/angular2-hapi-engine

**Comment by MarkPieszak** [comment]
What version of Universal are you including in your project? @maissani

**Comment by maissani** [comment]
"angular2-universal": "^0.104.1"

**Comment by gdi2290** [comment]
the systemjs helpers you're referring to that live inside of express-engine and hapi-engine are not meant to be used outside of this repo

**Comment by gdi2290** [comment]
for the new router support you must include `NODE_LOCATION_PROVIDERS` after the new router

```typescript
bootstrap(App, [
  provideRouter(routes),
  NODE_LOCATION_PROVIDERS,
])
```

**Comment by maissani** [comment]
Already done. 
Wait , i am diving with the errors and try to fix them
