### ISSUE TITLE
References errors Element, MouseEvent... not defined

### ISSUE THREAD

**Issue by thebarada** [angular/universal#529]
it occurs when using third-party plugins (etc ng2-bootstrap, angular2-masonry, clipboard).
There are errors such "Element, MouseEvent... not defined" when application run on server

**Comment by gdi2290** [comment]
this is because those are browser only types that

**Comment by Hongbo-Miao** [comment]
@thebarada please track this issue
https://github.com/valor-software/ng2-bootstrap/issues/964

**Comment by thebarada** [comment]
@gdi2290 @Hongbo-Miao 
ok, thnx!

**Comment by Hongbo-Miao** [comment]
@thebarada no problem, you can create an issue on angular2-masonry if need

**Comment by crebuh** [comment]
@thebarada 

I expierenced the same issue, but then I was wondering why to import the Ng2BootstrapModule on the server side?

**Comment by scott-wyatt** [comment]
@crebuh because it wouldn't really be isomorphic if you couldn't... However, the dirty work around is in the docs.  You can load any module and have browser side pick one side and node pick the other, however that leaves you with having to shim up module by module which also really defeats the point.  There is some promise in the new `createGlobalProxy` but it still pretty far off from shimming all browser functions.

**Comment by thebarada** [comment]
@crebuh do you mean that I should not import bootstrap on server?
but how I will use bootstrap components on server side?
in this case, when rendering will be errors about unknown components

**Comment by MarkPieszak** [comment]
Use ng2bootstrap @thebarada, it doesn't use jQuery or anything and should work.
