### ISSUE TITLE
NodePlatform's serializeModule returns a promise that resolves even if there was an error

### ISSUE THREAD

**Issue by SteveSandersonMS** [angular/universal#550]
* **I'm submitting a ...**
It's either a bug report or a feature request, depending on what the intended design is.

* **What modules are related to this Issue?**
- [x] universal

* **What is the current behavior?**

Given the following:

```
import { platformNodeDynamic } from 'angular2-universal';
const prerenderPromise = platformNodeDynamic().serializeModule(...);
```

... the `prerenderPromise` always resolves successfully, even if there was an error in the Angular app while serializing the module (e.g., a component's constructor threw, or there was a syntax error in a template that was being rendered).

* **What is the expected behavior?**

I'd expect the promise to be rejected if there was an error.

* **What is the motivation / use case for changing the behavior?**

Robust error handling.

* **Please tell us about your environment:**

All

* **Other information**

I'm building the ASP.NET Core SPA templates (which @MarkPieszak is very familiar with). Our server-side boot logic used to look like [this](https://github.com/aspnet/JavaScriptServices/blob/8f550c5706158dfb36a99c713b377acedbba8c47/templates/Angular2Spa/ClientApp/boot-server.ts), but I noticed that if you introduce an error into the app (e.g., try to evaluate `someNonExistentFunction()` in a template), then it just logs the error to the console but resolves the promise as successful, so the app renders without any obvious feedback that anything is wrong. Of course this makes it tricky for developers to understand any problems they might be experiencing.

To fix this, I've made the following change to capture Zone errors and force the promise to reject: https://github.com/aspnet/JavaScriptServices/commit/5214a553a7d98bc532b956af7ad14b8905302878?w=1

Could you provide feedback on:

[1] Is it really intended for `serializeModule` not to reject its promise on error? If so, to make it easier for developers to understand, could we have a flag called something like `abortOnError` in the `config` (the object that includes `baseUrl`, `preboot`, `document`, etc.) that configures it to reject the promise if there's an error in the zone?

[2] Possibly better still, have you considered exposing an API that encapsulates the plumbing around `Zone` etc. to simplify things further? For example, it could look like:

```
const prerenderPromise = platform.serializeModuleInZone(AppModule, {
    baseUrl: '/',
    document: '...',
    ...
});
```

Internally it would just call `Zone.current.fork` with an `onHandleError` that rejects the promise. Then developers don't even need to see the obscure-looking Zone stuff.

[3] For now, before any new APIs are added, is [this implementation](https://github.com/aspnet/JavaScriptServices/commit/5214a553a7d98bc532b956af7ad14b8905302878?w=1) what you would expect and consider correct for capturing errors?

**Comment by MarkPieszak** [comment]
(1) I don't believe so, there is an errorHandler inside of the `serialize` internal method within node-platform, but I think at the moment, it's important to pass in a `cancelHandler` within your platformConfig. @gdi2290 could explain this further. (I believe these might be more temporary things for now)

``` // Universal : node-platform.ts
serialize<T>(moduleRef: NgModuleRef<T>, config: any = {}): Promise<T> {
    var cancelHandler = () => false;
    if (config && ('cancelHandler' in config)) {
      cancelHandler = config.cancelHandler;
    }
```

[If you notice here](https://github.com/MarkPieszak/JavaScriptServices/blob/62dd13b3b8226500b828ad272e28e12dcea7955a/templates/Angular2Spa/ClientApp/boot-server.ts#L43-L49), this is why I originally had more code prior to serializing: 

    // defaults
    var cancel = false;

    const _config = Object.assign({
      get cancel() { return cancel; },
      cancelHandler() { return Zone.current.get('cancel') }
    }, platformConfig);

The serialize is looking for cancelHandler within the `config` so it can fire it off. 


(2) I like that idea! I do think that might definitely be simpler, we could at least abstract this logic into another method, since things like express-engine (which ends up creating a Zone.fork etc from it) depend on it as well.

(3) That's actually why I originally was doing the same thing and catching errors from the Zone, and returning the original document (since nothing got prerendered) ([here](https://github.com/MarkPieszak/JavaScriptServices/blob/62dd13b3b8226500b828ad272e28e12dcea7955a/templates/Angular2Spa/ClientApp/boot-server.ts#L58-L72)) Just setup a little differently than yours. (You cleaned it up nicely lol)

    return Promise.resolve(
        zone.run(() => {
            return platformRef.serializeModule(Zone.current.get('ngModule'))
        })
    ).then(html => {
        if (typeof html !== 'string' ) {
            return { html : doc };
        }
        return { html : html };
    }).catch(err => {
        console.log(err);
        return { html : doc };
    });

I do agree, this may not be the ideal way to handle this though!

I'm pretty sure things will change here to make life easier, this was more-so to get things going and update everything to the entire NgModule ecosystem.

Hopefully Pat can chime in and help explain things further.

**Comment by SteveSandersonMS** [comment]
Re (1) and (3) - some aspects of how that was implemented didn't seem to make sense to me (why use `Object.assign` to extend an object literal you've just created - why not just put the properties in the original object? What is the point of the `cancel` variable given that it's always going to remain `false` because nothing can write to it? Why chain a `catch` onto the final promise that returns an empty document (nothing writes to `doc`)? What is the point of the `if (typeof html !== 'string' ) { ... }` code branch given that it again returns an empty `doc` rather than what was rendered?). If I'm missing the point of any of these design decisions, please let me know.

> why I originally was doing the same thing and catching errors from the Zone

But does that code really catch errors from the Zone? It chains a `catch` onto the promise returned from `zone.run`, but that just passes through the result of the `platformRef.serializeModule` promise, which as per this issue always resolves and doesn't reject :)

I'd like to understand what the `cancelHandler` achieves and how it relates to error handling. From my experiments it didn't seem to relate to errors; only adding an `onHandleError` had the effect of catching them.

**Comment by MarkPieszak** [comment]
Apologies that was my fault, in our case the original object was coming in through parameters. Much of that code came from relating it to how it's done within the express-engine integration at the moment. So that's my fault I should of cleaned it up a bit :(
The cancel variable is also moot, used within the way we're integrating it there as well.

Let me do some more testing to see if I can figure out what we're missing on our end here!

**Comment by MarkPieszak** [comment]
@gdi2290 So I think what we're simply missing here is a `catch` on serializeModule that *further* throws a catch to whatever originally called it (be it express-engine, or in this case, .NET with the Zone.run())

@SteveSandersonMS So with this setup, you could do that `catch` that we were talking about, but instead of receiving **html** it'll be an error stacktrace, which you could pass onto the browser (like I did here).

![image](https://cloud.githubusercontent.com/assets/2574412/18724693/4e325cc8-800b-11e6-9ab2-3733e13b8a2d.png)

In my case the only additions I needed were:

 [node-platform.ts] **`serializeModule`**:

      // ... .then() chain
      .catch(e => {
          throw e;
      });

**`express-engine`** (Steve you wouldn't need to worry about that part).

    // inside readContent, the Zone.run()
    .catch(function (e) {
          console.log(e.stack);
          done(null, 'Angular Universal - Server-side ERROR :: <br><br>' + e.stack);
    });

Let me know what you guys think.

**Comment by gdi2290** [comment]
can you try `angular2-universal` 2.1.0-rc.1 where this is merged. thanks!

**Comment by viktorstaikov** [comment]
Hi,
Same problem here.
I'm using angular2-universal 2.1.0-rc.1 as you've mentioned. 
Through debugging I've found that the error is thrown at NodePlatform.serialize -> asyncPromiseSeries -> destroyAppAndSerializeDocument -> destroyApp(). The error was inside ngOnDestroy() hook. 
In fact, there is _reject_ there, but somehow it is lost and not propagated properly to the promise chain.
