### ISSUE TITLE
(feat):streaming universal with express

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal#561]
expose a synchronous function to get rendered component , so that It can be streamed to the client

Example : 

<img width="560" alt="screen shot 2016-09-29 at 5 03 16 pm" src="https://cloud.githubusercontent.com/assets/10448534/18952342/dd31a148-8666-11e6-90cb-f95fe26531e9.png">

**Comment by gdi2290** [comment]
Thanks for the issue and looking into server rendering perf. So it turns out you actually don't want a synchronous function since it blocks the event loop like React's rendering current does. You can do the same with Angular 2 the only problem is dealing with DOM mutations that might happen within your application such as Angular itself is doing for styles. Right now the current solution is good enough until we create a better streaming API support which is on the roadmap. 


Here are some problems with streaming that we're considering. If someone creates a service in Angular that changes the metadata then that won't be reflected in the DOM sent to the client since it was streamed down already. If we stream down each element at a time and midway through rendering the document a child component changes the view of it's parent then the parent's DOM has already been sent down to the client. For a great component streaming story we would need to attach more metadata to each component where the developer can determine if the component doesn't rerender etc

**Comment by kuldeepkeshwar** [comment]
@gdi2290 I do see a use-case for SEO here where it requires having `<html>` as root component to set meta tags according to content on the page ,but this can be solved by booting `<head>` and `<app>` separately and having a centralize service (providing pre-determined meta tags) for SEO.

  instead of having a synchronous function(which will definitely block everything) we can use callback/promise to get rendered component.
