### ISSUE TITLE
Component IDs are Misaligned between Client and Server

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/universal#573]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**

bug
- **What is the current behavior?**

Each Renderer assigns Component Style IDs isolated from one another and there is no transfer to the client. What this results in is that if the server is entering the app from one component and the client is entering the app from another, The 2 renderers will conflict which one another and the styles will be applied to the wrong elements.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

https://github.com/FrozenPandaz/universal-starter/tree/multiapp

Note that the server comes in from the Html Component and the client comes in from the App1 Home component.
- **What is the expected behavior?**

The Server Renderer should provide the Client Renderer with a state to extend from so that the client doesnt override elements with different component IDs
- **What is the motivation / use case for changing the behavior?**

This is to synchronize the Server and Client rendering so that the styles dont get shifted to the wrong elements
- **Please tell us about your environment:**
- Angular version: 2.0.0+
- Browser: [all]
- Language: [TypeScript 2.0.0+]
- OS:  [all]
- Platform: [NodeJs]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
The problem here is when you include UniversalModule in more places other than just the root module. The real issue is APP_ID which is cached when creating a module factory which needs a core change. In UniversalModule we're creating a new APP_ID for each time UniversalModule is included which is causing this problem

see repo for repo
https://github.com/FrozenPandaz/universal-starter

**Comment by FrozenPandaz** [comment]
As we discussed, this is not the issue and is actually an issue in core right?

**Comment by thebarada** [comment]
+1

**Comment by gdi2290** [comment]
here's the workaround
https://github.com/angular/universal-starter/blob/d33e7353f9404779291d66c7acfc480f5880b3db/src/server.ts#L6...L11

**Comment by thebarada** [comment]
@gdi2290 sounds good, but unfortunately not working
I import UniversalModule only on browser and node module
but still have problems with styles

**Comment by gdi2290** [comment]
@thebarada are you using html component or are you only bootstrapping one app in the document?

**Comment by thebarada** [comment]
@gdi2290 what do you mean?
I'm bootstrapping only one app in this way:
```
document.addEventListener('DOMContentLoaded', () => {
  
  platformRef.bootstrapModule(AppModule);
  
});
```

**Comment by thebarada** [comment]
@gdi2290 I've tried bootstrap app immediately (without DOMContentLoaded listener) and problem with styles was gone
but there was new problem - with universal cache
`universal-script` added to and of body, and when application is bootstrapping there no universal cache yet

**Comment by gdi2290** [comment]
@thebarada universal-script was purposely set at the bottom of the page which forces the developer to bootstrap only on document ready. Do any dom manipulation before the document ready cause a lot of perf problems during initial render. I can provide you with a snippet to move universal-scripts higher or anywhere in the document. For this issue is a problem with core and how it's managing style and scope for when we use an html component which includes the app on the server and the client app with doesn't use the html component. 

Angular core can't support html component at this time so I have to close this issue as it's an intended effect. 

@thebarada if you have style issues can you recreate the problem using the universal-starter and open another issue that way I can get it fixed for you asap

**Comment by HonnKing** [comment]
@gdi2290 What does "can't support html component" mean? I've hit a similar problem to this (ViewEncapsulation gone awry, sounds likely that it's the same thing) and I don't quite get what you mean in this case.

Is there some specific way you need to boostrap you app?

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
