### ISSUE TITLE
ngconfig.json is a bad pattern

### ISSUE THREAD

**Issue by alexeagle** [angular/universal#576]
I created the `ngc` configuration in such a way that it can live in the `tsconfig.json` file along with typescript settings.
Ultimately the plan is for `tsc` to replace `ngc` once the extensibility-model branch is worked out.

Users should not need a separate copy of their `tsconfig.json` just to run ngc on it. This antipattern exists in the universal examples which makes me concerned that lots of users are copy-pasta into their apps and losing maintainability and reproducibility...

**Comment by MarkPieszak** [comment]
Good idea!

Another thing is maybe we should re-label the "examples" to "testing-playground" or some other name. It's used just so that we can test changes made to Universal/etc modules, and run through some live pseudo scenarios. Ideally we don't want people to follow what's going on in those since the setup is crazy!

**Comment by gdi2290** [comment]
good point. `/examples` should be renamed to `/playground`. the examples folder was also confusing other developers

**Comment by gdi2290** [comment]
As mentioned in ngTeam slack, ngc has problems with multiple entry files. For example, if I have `app.browser.module.ts` and `app.node.module.ts` ngc will say that the `App` component is used in two MainModules which is true but they are separate entry files. Also in those files I also need to import a direct path to the platform so `angular2-universal/node` and `angular2-universal/browser` rather than `angular2-universal` which uses the package.json browser field
https://github.com/defunctzombie/package-browser-field-spec

tsAlex also mentioned [Microsoft/TypeScript/issues/9876](https://github.com/Microsoft/TypeScript/issues/9876) typescript@next has this feature to help with this

**Comment by gdi2290** [comment]
closing this since we need to create a tsconfig for each platform
