### ISSUE TITLE
'ngc' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#608]
- **I'm submitting a ...**
- [X] bug report
- OS:  **Windows** (Note: works fine on MAC etc)

On Windows, the `gulp` command can't properly run and breaks on Build during the spawn childprocess exec of **`ngc`**.

Looking into alternatives to get it working cross-platform.

Worth looking into alternative ways of running _ngc_ such as the way @mgechev does it [here](https://github.com/mgechev/angular-seed/blob/faa9f1929c3ea4c16ebc60e1dad47913acb7db83/tools/tasks/seed/compile.ahead.prod.ts)
@steve8708

**Comment by steve8708** [comment]
@MarkPieszak unfortunately I'm not able to test with windows, but I'm sure the culprit is the path notation in line 62 of `gulpfile.ts`

```ts     
child_process.exec('node_modules/.bin/ngc', (err, stdout, stderr) => {  
```

you could try changing that to

```ts     
child_process.exec(path.resolve('node_modules', '.bin', 'ngc'), (err, stdout, stderr) => {  
```

or if for some reason that doesn't work, add to `package.json`

```json
"scripts": {
  "ngc": "ngc"
}
```

and use

```ts     
child_process.exec('npm run ngc', (err, stdout, stderr) => {  
```

it would be good to update the `_test` gulp task too as if `ngc` doesn't work on windows `_test` won't either as they both use the same notation to reference npm install'd executables

**Comment by MarkPieszak** [comment]
Thank you @steve8708 that's what I figured as well, works like a charm! PR #610
