### ISSUE TITLE
[Documentation] Link to UniversalCache not found

### ISSUE THREAD

**Issue by dverbovyi** [angular/universal#634]
Hi, 
I'm submitting a small minor bug report related to documentation README.md.

The current behaviour is missed link to UniversalCache mentioned here: [https://github.com/angular/universal#universal-gotchas]()

Please, take a look on it

**Comment by MarkPieszak** [comment]
Updated the ReadMe: https://github.com/angular/universal/pull/635

Thanks for spotting that!

Updated to: 

- Use a [UniversalCache](https://github.com/angular/universal-starter/blob/master/src/%2Bapp/shared/model/model.service.ts#L34-L50) instead of regular Http, to save certain requests so they aren't re-ran again on the Client. ([Example useage here](https://github.com/angular/universal-starter/blob/cc71e2d5b2d783f2bb52eebd1b5c6fa0ba23f08a/src/%2Bapp/%2Bhome/home.component.ts#L22-L24))

**Comment by dverbovyi** [comment]
thank you
