### ISSUE TITLE
Recommended way to handle redirects server side if angular service throws error due to 500s, etc?

### ISSUE THREAD

**Issue by ScaryWolfMan** [angular/universal#675]
I am handling 404s static page redirects through express, but how can I redirect to my 500 internal error page if my REST API is down or something?

I have some complex components and if the REST API is down, I would like to redirect to my error page and on client side, I can do this using `window.location.href`, but how would I handle this in the angular component code on the server side?

Again, I know how to do this in express but this error would be thrown in angular component code.  

One approach I am exploring is using a global helper in my express application where any instance of a 500 from an API response would trigger it to cause a express redirect.  However, I'm sure there are some better approaches :)

Thanks

**Comment by diestrin** [comment]
You can have a route to the ngApp for 500 errors, register that same route on angular router. In your component then redirect to the 500 error page. I do something similar for 404 pages on routes like /article/:title when the title doesn't exists.

You can do the redirect without changing the url, so that's not a problem :)
