### ISSUE TITLE
Get http request on server side works but not display on client side [Angular Universal(universal cli)]

### ISSUE THREAD

**Issue by vforv** [angular/universal#677]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

Any help guys:

http://stackoverflow.com/questions/42880305/get-http-request-on-server-side-works-but-not-display-on-client-side-angular-un

**Comment by MarkPieszak** [comment]
angular2-universal has since moved to @angular/platform-server within Angular Core, can you try upgrading your project and see if this issue has been fixed? Closing this out for now.

Also note the universal-cli has been deprecated, there are some efforts to create some support within the angular-cli but it will be a bit different.

You can check out the upgrade guide from angular2-universal -> platform-server we have here as well: https://github.com/angular/universal/blob/master/UPGRADE-GUIDE.md
