### ISSUE TITLE
focus on <input> cursor position differs between server rendered and client rendered

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#68]
given an html element
```html
<input value="testing" autofocus [value]="value" (keyup)="value = $event.target.value">
```
the cursor position is at the beginning `[|testing]` for server rendered view. Then preboot.js transfers the focus back `[testing|]` the cursor position is now the latest position and value. Also note that angular doesn't save the cursor position when a user types in a new value. This probably due to setting the `[value]` on keyup

**Comment by manekinekko** [comment]
I did some tests about the second point you mentioned (angular not saving the cursor position). 
Removing the biding of **[value]** (I know this is not a solution), but doing so seems to fix this specific issue. However, the initial value of **value** is obviously not bound...

 ```html
<input value="testing" autofocus value="value" (keyup)="value = $event.target.value">
                                 ^^^^^^^^^^^^
```

I will continue digging...

**Comment by gdi2290** [comment]
this might be a browser thing

**Comment by tbosch** [comment]
We should change `preboot.js` to also store the caret position using `input.selectionStart = input.selectionEnd = <caretPosition>`.

**Comment by gdi2290** [comment]
@jeffwhelpley what do you think?

**Comment by manekinekko** [comment]
I was thinking of suggesting something like this:

```javascript
// in event_manager.ts@addEventListeners()

// ...
state.eventListeners.push({
      node: node,
      name: eventName,
      handler: handler,
      selection: getCursorPosition(preboot, node)  //<--- capture the carret position
});
//...
````

```javascript
// generic solution found on SO...
// http://stackoverflow.com/questions/2897155/get-cursor-position-in-characters-within-a-text-input-field?answertab=active#tab-top
export function getCursorPosition(preboot: PrebootRef, node: Element) {
  var iCaretPos = 0;

  // IE Support
  if (preboot.dom.state.document.selection) {

    // Set focus on the element
    node.focus();

    // To get cursor position, get empty selection range
    var oSel = preboot.dom.state.document.selection.createRange ();

    // Move selection start to 0 position
    oSel.moveStart ('character', -node.value.length);

    // The caret position is selection length
    iCaretPos = oSel.text.length;
  }

  // Firefox support
  else if (node.selectionStart || node.selectionStart == '0')
    iCaretPos = +node.selectionStart;

  // Return results
  return (iCaretPos);
}
```


May the `state.eventListeners` array is not the place where to store the caret information, but I thought that when replaying events of a certain Node, we could replay the selection record as well.

**Comment by jeffwhelpley** [comment]
Thanks, @manekinekko for the tip. I am trying out some changes now to preboot that will use a version of this code. I am putting the code for getting caret position and setting caret position in the dom wrapper since there is some browser specific hackery going on there. As a general rule, FYI, the dom wrapper should be used to abstract out any and all browser hackery (sort of like a mini-jQuery). I will try to have something checked in later tonight or tomorrow morning.

**Comment by manekinekko** [comment]
Awesome! thanks @jeffwhelpley

**Comment by manekinekko** [comment]
hi @jeffwhelpley I grabbed your PR and tested it locally. Here what I experienced...

**My tests were:**
- TEST1: I do a select all before preboot completes.
- TEST2: I move the cursor to a specific position.
- TEST3: I insert few letters at an arbitrary position.

**FYI, I reloaded the page between each test and my network is set at 3G (in devtools) **

![preboot-caret-bug-jeff-patch](https://cloud.githubusercontent.com/assets/1699357/9208055/a1c78a14-4071-11e5-8dbd-38d31d950d01.gif)

**Comment by jeffwhelpley** [comment]
@manekinekko what browser are you using?

one thing I know has to change is that I am not changing the stored cursor position based on mouse movements. I can fix that, but I want to make sure I cover everything else. If you don't change the cursor with your mouse is there still an issue in whatever browser you are using?

**Comment by manekinekko** [comment]
For the GIF about, I am using Chrome 44.0.2403.130.
Yes, I can tell you that when I move the cursor using the arrow keys, preboot remembers as expected the cursor position, in Chrome!

Safari and Firefox (nightly) have different behaviours...

### Safari 8.0.8 (10600.8.7)

On page load, and before preboot completes, Safari selects all input content. Perhaps because of the focus event!

![preboot-caret-bug-jeff-patch-safari](https://cloud.githubusercontent.com/assets/1699357/9210424/87975cae-407c-11e5-85b4-5694f65ac539.gif)

### FireFox nightly 42.0a1 (2015-08-11):

Firefox (nightly) completely looses focus when preboot completes.

![preboot-caret-bug-jeff-patch-ff-nightly](https://cloud.githubusercontent.com/assets/1699357/9210433/98cb940e-407c-11e5-9c28-823f2b059dba.gif)

Sorry, I dont have a Windows machine in order to test IE.

**Comment by jeffwhelpley** [comment]
Interesting. OK, I will figure out what is going on with FireFox and Safari as well as the mouse events. We can worry about IE after that.

**Comment by jeffwhelpley** [comment]
I just updated my PR with changes that include selection of text. I have validated this works on modern Chrome, Safari and FireFox browsers. I wasn't quite sure how to test this on IE so I am hoping someone here has a Windows machine and can try this out.
