### ISSUE TITLE
Update quickstart or take it down

### ISSUE THREAD

**Issue by benrondeau** [angular/universal#745]
Based on issues like #673, please update or take down https://universal.angular.io/quickstart. It is outdated and leads devs on a wild goose chase to make it work (if they can at all).

Just copying the content [here ](https://github.com/angular/universal/blob/master/UPGRADE-GUIDE.md) to quickstart would be a huge step forward. I'll even do the work myself and submit a PR if that helps.

Much thanks.

**Comment by BurningDog** [comment]
Agreed.

1.3.0 release of @angular/cli has experimental Angular Universal support: https://github.com/angular/angular-cli/releases/tag/v1.3.0

The guide it points to is https://github.com/angular/angular-cli/wiki/stories-universal-rendering

This is a big step forward, because most people use angular-cli for running Angular projects, but the Angular Universal example repo at https://github.com/angular/universal-starter doesn't.

Once Angular Universal support is stable in Angular CLI, I'd suggest pointing to those instructions instead.

**Comment by Toxicable** [comment]
https://github.com/angular/universal-starter now has an example which includes the CLI.
https://universal.angular.io/quickstart jsut needs to be updated to point there

**Comment by TomasKatz** [comment]
I agree the aspdotnet core is completly broken

**Comment by Toxicable** [comment]
fixed  https://universal.angular.io now redirects to the angular.io Universal guide
