### ISSUE TITLE
socket.io with ssr

### ISSUE THREAD

**Issue by matheusdavidson** [angular/universal#846]
Does universal work with socket.io? and how to?

**Comment by Toxicable** [comment]
This is sort of a tricky question. 
Universal can work with socket.io but you have to use it a in a different way.
By default Universal waits for all async operations to complete before rendering to a string, this includes things like http requests, promises, Observables and WebSockets.
Since Web Sockets are long lived they stay open and will actually block the app from rendering on Universal so you need to somehow close this connection so that Universal can render.

Sorry I can't provide specifics on how to do this since i've never used socket.io

**Comment by CaerusKaru** [comment]
> By default Universal waits for all async operations to complete before rendering to a string

@Toxicable do you have a source on this? It was my understanding that the render process calls all server hooks, then bootstraps the app (which only waits for the bootstrap process to complete, async or no). For instance, #842 deals with an Observable HTTP request, where the application does not wait for completion.

@matheusdavidson socket.io should work assuming the client you're using is Universal compatible (i.e. doesn't try to reference `document`, or `window`) and pulls in its own version of WebSocket for Node (I know this is an issue with Apollo atm, but socket.io I think is fine). The only issues you may face come with duplicate requests, since TransferStateHttpModule does not work with `wss` connections, which may result in flicker. You can of course disable socket.io on the server by only including it in a browser-specific module or by placing socket calls behind `isPlatformBrowser` checks.

**Comment by Toxicable** [comment]
@CaerusKaru This here 
https://github.com/angular/angular/blob/d2707f14574bdfd4ea0c0ecf3d85383f6d54186a/packages/platform-server/src/utils.ts#L46

**Comment by CaerusKaru** [comment]
Ok I see what you mean, but in this case I think I'm confused by what you mean by waiting. When a Zone catches an operation, it simply makes sure to execute the operation in the correct Zone, it doesn't actually wait for the call to succeed/respond first (see example [here](https://github.com/angular/zone.js/blob/master/NON-STANDARD-APIS.md#usage)). As I understand it, Zones are simply meant to encapsulate VM ticks so that everything occurs in the proper sequence, not to enforce synchronous processing for asynchronous events.

**Comment by Toxicable** [comment]
If you take a look here
https://github.com/angular/angular/blob/14e8e880222431eeccdacac6540574b49903bd79/packages/core/src/application_ref.ts#L409
`isStable` is just an Observable which emits when there are no tasks in the queue, meaning, there are no outstanding async events being tracked

**Comment by CaerusKaru** [comment]
What it means is that there are no remaining async events that need to be executed in the current Zone (Promises/Observables in this case being microtasks), since those tasks get saved for the end of the VM tick. It has nothing to do with the tasks being tracked.

**Comment by Toxicable** [comment]
I think you misunderstand, async events remain in the queue until they are resolved, one way or another.

**Comment by Toxicable** [comment]
here's a small demo showing this
https://stackblitz.com/edit/angular-gitter-uwkzvd?file=app%2Fapp.component.ts

**Comment by CaerusKaru** [comment]
setTimeout is a macrotask, which as you have pointed out do get tracked to completion. Microtasks, as far as I can tell, do not.

**Comment by CaerusKaru** [comment]
Just by the by, in your demo, what gets printed in my console is the following:

```
app.component.ts:27 stable
console.js:27 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
app.component.ts:28 timeout done
app.component.ts:27 stable
```

Which might explain why renderModuleFactory doesn't wait for the async calls to complete, because it only takes the first `isStable` tick completion.

**Comment by Toxicable** [comment]
Yeah that's probably not the best of demos, since that's not how it works in with `renderModuleFactory `'s one, since it *does* wait for async operations such as HttpClient calls

**Comment by CaerusKaru** [comment]
Ok, then I apologize for all the confusion, you are right about Zones in general, just not in the context of this thread as applied by `renderModuleFactory`. I'll remove all of my followup comments (including this one), and amend my first comment to reflect this.

**Comment by CaerusKaru** [comment]
After throwing together a basic WebSocket example, which socket.io will use if available, it looks like WebSockets are not tracked by Zones (@Toxicable feel free to take a look and correct me if I'm missing something). [Here](https://stackblitz.com/edit/angular-gitter-9akamn?file=app/app.component.ts)'s the example on StackBlitz, running the WebSocket echo test and then closing the socket. I also updated the appRef subscribe to match what `renderModuleFactory` does.

**Comment by Toxicable** [comment]
@CaerusKaru WebSockets are tracked be Zones, you can see that by putting `NgZone.assertInAngularZone()` inside the handler event. Also you can see the patch here
https://github.com/angular/zone.js/blob/a66595af18d4c42584401dd2df387b02cb01d8d9/lib/browser/websocket.ts

However as I mentioned above, WebSockets are long lived, they stay open untill they are closed. In your example the WebSocket is never closed, that's why you don't see the stable event fire and why Universal wont work with socket.io or firebase without special handling for the websockets

**Comment by CaerusKaru** [comment]
@Toxicable on line 25 the socket is closed once the message is received.

After looking into this a little more, this is apparently a [documented and long-lived issue](https://github.com/angular/zone.js/issues/381). However, I think the one advantage Universal has in this case is that I think it's almost guaranteed this won't hold up rendering, since the appRef call is almost immediately invoked after the components render (ie the initial view is stable, and then immediately not stable). But if this turns out not to be the case after testing, the recommendation would be (1) move socket.io into the browser build only or (2) run all socket.io-related code outside the Angular Zone, which may result in a performance hit/change-detection issues.

**Comment by Toxicable** [comment]
@CaerusKaru Whops, sorry missed that line, in that case I don't know whats going on in that example.

While both of those could be a solution, I personally think comming up with another way / api for handling when to render on the server should be investigated.

**Comment by CaerusKaru** [comment]
@Toxicable I think that's a great idea! Some consistency would be a relief. Do you want to open a new issue to track the feature? I have some preliminary ideas that should probably go there.

**Comment by Toxicable** [comment]
@CaerusKaru sure, but open it up on the angular repo since that's where this stems from

**Comment by CaerusKaru** [comment]
Tracking here: https://github.com/angular/angular/issues/20520

**Comment by matheusdavidson** [comment]
I did try but ended up using socket only in the browser build because as you guys pointed out angular doesn't finish rendering the page, probably its waiting for a response from the socket event.

Not sure if closing the connection all the time i receive a response would be very good because we could have other code waiting for socket events.

Maybe an option would be using [socket.io with promises](https://github.com/perrin4869/socket.io-as-promised), i will try this when i have some time.

**Comment by vikerman** [comment]
Hi - You can make a task trackable by Zone.js by doing something similar to here

https://github.com/angular/angular/blob/14e8e880222431eeccdacac6540574b49903bd79/packages/platform-server/src/http.ts#L38

Would that satisfy your use case?

**Comment by hiepxanh** [comment]
any update on this? Can you write some instruction ? My firebase application need to use that, hope you can help. @vikerman

**Comment by Ks89** [comment]
It is very useful an official example with server + client using socket.io.
I tried to include it in my server code (based on the official node.js example with express) but it isn't working.

```
> project@1.0.0-beta.1 serve:ssr /Users/ks89/git/project
> node dist/server.js

/Users/ks89/git/project/dist/server.js:160136
    return /*require.resolve*/(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                               ^

Error: Cannot find module "."
    at webpackMissingModule (/Users/ks89/git/project/dist/server.js:160136:76)
....
```

**Comment by DominikTrenz** [comment]
A workaround in my case was to force close the socket after a certain time. It increses the render time but it works:

```
this.socket = io(this.wssEndpoint);
setTimeout(() => {
     this.socket.close();
}, 10000);
```

I can't wait to see a more elegant solution :)

**Comment by professphysics** [comment]
I have not worked on it yet. **Intuitively speaking**, I'd bind every established connection with an authorizing mechanism (say: JWT stored in a cookie). when the server tries to build a connection (ironically=> with itself), I'd have to cut the connection immediately due to an unauthorized connection (authorization test fails).
 I may come back with code -> if anyone is in need let met know :)

**Comment by takahser** [comment]
how about rxjs support? it didn't work with my when using rxjs for websocket communication (see: https://github.com/angular/universal/issues/1042)

**Comment by ignazioa** [comment]
@Ks89 , We are experiencing the same error with Express + Universal. Were you able to find a solution ?

```
Error: Cannot find module "."
    at webpackMissingModule (/Users/ks89/git/project/dist/server.js 
```

**Comment by ulrichdohou** [comment]
Check this. an answer on stackoverflow. You need to detect if it is browser of or server side.
[https://stackoverflow.com/a/41721980/6261137](url)

**Comment by sean-nicholas** [comment]
I found a solution that works for me. I'm using feathers.js and don't handle the socket directy. The second step is therefore a guess how it works with pure socket.io.

There is somewhere a similar issue where I found parts of the solution, but I could not find it anymore - so thanks original author :)

First, the socket creation needs to run outside of angular:

```ts
this.ngZone.runOutsideAngular(() => {
  this.socket = io(this.BASE_URL)
})
```
Second, the `on` callback needs to run in the zone again (don't ask me why :D)
```ts
this.socket.on('message', (data) => {
  ngZone.run(() => {
    doStuff(data)
  })
})
```
Now it should work, but you just have created a memory leak because the socket does not get closed. You need to add a ngOnDestroy method to your service that created the socket:
```ts
ngOnDestroy(): void {
  this.socket.close()
}
```
---
For completeness here is my code that works with feathers.js:

data.service.ts:
```ts
import { Services } from './../../../../shared/types/services'
import { Injectable, NgZone, OnDestroy } from '@angular/core'
import { environment } from '../../environments/environment'
import feathers, { Application } from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import * as rx from 'feathers-reactive'
import * as io from 'socket.io-client'
import { ngFeathersWebsocketSupport } from '../../lib/ng-feathers-websocket-support'

@Injectable()
export class DataService implements OnDestroy {
  constructor(
    public ngZone: NgZone
  ) {
    this.init()
  }

  BASE_URL = environment.dataUrl
  app = feathers() as Application<Services>
  socket: SocketIOClient.Socket = null

  protected init() {
    this.ngZone.runOutsideAngular(() => {
      this.socket = io(this.BASE_URL)
      this.app
        .configure(socketio(this.socket, {
          timeout: 10 * 1000
        }))
        .configure(rx({ idField: '_id' }))
        .configure(ngFeathersWebsocketSupport({ ngZone: this.ngZone }))
    })
  }

  ngOnDestroy(): void {
    this.socket.close()
  }
}
```
ng-feathers-websocket-support.ts:
```ts
export function ngFeathersWebsocketSupport(options: { ngZone: any }) {
  const mixin = function (service) {
    const originalOn = service.on.bind(service)

    const serviceMixin = {
      on(event, cb) {

        return originalOn(event, (...args) => {
          options.ngZone.run(() => {
            cb(...args)
          })
        })
      }
    }

    // get the extended service object
    service.mixin(serviceMixin)
  }

  return function (app) {
    app.mixins.push(mixin)
  }
}
```
Hope this helps anyone :)

**Comment by sanjaynishad** [comment]
Simply we can check for `browser` and initilize the `socket` things
 
    import { isPlatformBrowser } from '@angular/common';
    import { Inject, PLATFORM_ID } from '@angular/core';

    constructor(@Inject(PLATFORM_ID) private platformId: Object) {
      if(isPlatformBrowser(this.platformId)) { // check if this is runing in browser
        this.socket = io('http://localhost:3000/'); // call io constructor
        this.init(); // do the all initilization, e.g. this.socket.on('message', msg => {})
      }
    }

**Comment by hsuanyi-chou** [comment]
@sean-nicholas 
thank you so much !! it works !
by the way, using fromEvent in RxJs makes code much more clean.
in `Websocket.service.ts`

```
@Injectable({
  providedIn: 'root'
})
export class WebsocketService implements OnDestroy {

    private url = 'ws://localhost:4001'; // 上Server的話，要改成Server IP！
    private socket: SocketIOClient.Socket;

    constructor(private readonly ngZone: NgZone) {

      this.ngZone.runOutsideAngular(() => {
        this.socket = io(this.url, {
          reconnection: true,
          reconnectionDelay: 5000,
          reconnectionAttempts: 5,
        });
      });

      this.on$('connection').subscribe(console.log);
      this.on$('error').subscribe(console.log);
      this.on$('wsException').subscribe(console.log);
      this.on$('connect_error').subscribe(console.log);
    }

    emit(channel: string, emitValue: any) {
      this.socket.emit(channel, emitValue);
    }
    on$(channel: string) {
      return fromEvent(this.socket, channel);
    }

    off(channel: string) {
      this.socket.off(channel);
    }

    ngOnDestroy() {
      this.socket.close();
    }
}
```

in `Other.Component.ts`
```
  ngOnInit() {
    this.websocketService.on$('message').subscribe((message:any) => {
      this.ngZone.run(() =>{
            this.message = message;
            this.changeDetectorRef.markForCheck()  // if you need.
    });
   this.websocketService.emit('message', 'emit a message to server');
}
```

**Comment by Twois** [comment]
@sean-nicholas @hsuanyi-chou

I tried these solutions, but what about the acknowledgements (callback) in the emit method, because in this case we are not able to wait for that.

Actually I implemented a queue system, and wait for the response form the server, and if the queue is get emptied I close the connection.

**Comment by hsuanyi-chou** [comment]
@Twois
in `WebsocketService`, we have `on$`.
```
//.... 
   on$(channel: string) {
      return fromEvent(this.socket, channel);
    }
```

in `Other.Component.ts`, use `on$` to subscribe and will be received the data when socket.io server emitted.
```
//...
   ngOnInit() {
        this.WebsocketService.on$('message').subscribe(data =>
            this.ngZone.run(() =>{
               this.message = message;
               this.changeDetectorRef.markForCheck()  // if you need.
            }
    });
   }
//...
```
you can send any keyword (replace 'message') you like to listen to.

remember using `ngZone` in the subscribe callback function.

**Comment by Twois** [comment]
@hsuanyi-chou 

I speak about this case:

`
    emit(channel: string, emitValue: any, cb: Function) {
      this.socket.emit(channel, emitValue, cb);
    }
`
In this case the angular won't wait for the response of the server.

**Comment by HHGAG** [comment]
This could be a solution:
https://stackoverflow.com/a/41721980

**Comment by agcarlosandres** [comment]
@ulrichdohou Muchas gracias! la solución que presentaste planteada aqui: https://stackoverflow.com/a/41721980/6261137 me ayudo a resolver el problema... me salvaste!

**Comment by agcarlosandres** [comment]
> Check this. an answer on stackoverflow. You need to detect if it is browser of or server side.
> [https://stackoverflow.com/a/41721980/6261137](url)

Esta solución es sencilla y efectiva

**Comment by Chef211** [comment]
> Does universal work with socket.io? and how to?

I’m just a beginner trying to understand the
 business, maybe it can help me in my
writing and illustration of children’s books.

**Comment by xtianus79** [comment]
@Chef211 wth?

**Comment by xtianus79** [comment]
@Twois or @hsuanyi-chou @sanjaynishad @sean-nicholas Would any of you mind helping me out with this. I am a little lost

**Comment by sean-nicholas** [comment]
Hey @xtianus79 Whats your problem? Can you give some context? Have you tried the solutions above? What's working / what's not?

**Comment by xtianus79** [comment]
@sean-nicholas so I am in the middle of trying what you are speaking of and this other solution that is working per se and seems like a hack. 

Let me show you what I have:
this is the SSE service, same would go for websockets. 

```javascript
import { isPlatformBrowser } from '@angular/common';
import { Injectable, NgZone, Inject, PLATFORM_ID } from "@angular/core";
import { Observable } from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class SseService {

  private isBrowser: boolean = isPlatformBrowser(this.platformId);

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    private _zone: NgZone
    ) {
      if (this.isBrowser) {
        console.log('this happened here');
      }
     }

  getServerSentEvent(url: string): Observable<EventSource> {
    return Observable.create(observer => {
      const eventSource: EventSource = this.getEventSource(url);
      eventSource.onmessage = event => {
        this._zone.run(() => {
          observer.next(event);
        });
      };
      eventSource.onerror = error => {
        this._zone.run(() => {
          observer.error(error);
        });
      };
    });
  }
  private getEventSource(url: string): EventSource {
    if (this.isBrowser) {
      console.log('this happened here 2');
      return new EventSource(url);
    }
    
  }
}
```

this is the implementation. 
```javascript
ngOnInit() {
    this.sseService
      .getServerSentEvent('http://localhost:4201/user/stream')
      .subscribe(data => console.log('data here >>>>> ', data));
```

**Comment by sean-nicholas** [comment]
@xtianus79 Okay, so I'm not quite sure if you need the runOutsideAngular if you are using server sent events. But if you do, I would think that this might work (just a guess, it's long ago that I implemented my solution and I don't know SSE)

```ts
getServerSentEvent(url: string): Observable<EventSource> {
    return Observable.create(observer => {
      this._zone.runOutsideAngular(() => {
        const eventSource: EventSource = this.getEventSource(url);
        eventSource.onmessage = event => {
          this._zone.run(() => {
            observer.next(event);
          });
        };
        eventSource.onerror = error => {
          this._zone.run(() => {
            observer.error(error);
          });
        };
      });
    });
  }
```

The `isPlatformBrowser` function is not a hack at all. I use it all the time. And especially in your use case it makes sense because `EventSource` does only exist in the browser and not in node.js. Therefore you need to make that distinction.

But I think you should return an EventSource mock from `getEventSource` if you are on the server  otherwise `const eventSource` would be undefined and `eventSource.onmessage` would fail.

**Comment by nauraizmushtaq** [comment]
Hi,
I'm using Angular SSR with ASP.Net using SPA Services. Application became irresponsive when i pass 1K concurrent request using apache JMeter or WebSurg. Most of the time connection timeout shows up or application took more then 120 secs to load the home page.

It would be very helpful if someone could suggest a possible solution

**Comment by GNP1988** [comment]
> Simply we can check for `browser` and initilize the `socket` things
> 
> ```
> import { isPlatformBrowser } from '@angular/common';
> import { Inject, PLATFORM_ID } from '@angular/core';
> 
> constructor(@Inject(PLATFORM_ID) private platformId: Object) {
>   if(isPlatformBrowser(this.platformId)) { // check if this is runing in browser
>     this.socket = io('http://localhost:3000/'); // call io constructor
>     this.init(); // do the all initilization, e.g. this.socket.on('message', msg => {})
>   }
> }
> ```

work fine for me

**Comment by mazba07** [comment]
Simply call WebSocket only in the browser mood. Follow the answer. 
https://stackoverflow.com/a/41721980/5978179

Here is my socket Service 
-----------------------------
import { Inject, Injectable, PLATFORM_ID } from '@angular/core';
import { io } from 'socket.io-client';
import { Observable } from 'rxjs';
import { isPlatformBrowser } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class SocketServiceService {

  isBrowser: boolean | undefined;
  socket: any;
  // uri: string = "ws://localhost:3000";
  uri: string = "http://localhost:3000";

  constructor(@Inject(PLATFORM_ID) platformId: Object) {
    this.isBrowser = isPlatformBrowser(platformId);
    if (this.isBrowser) {
      this.socket = io(this.uri);
    }
  }

  listen(eventName: string) {
    return new Observable((subscriber) => {
      this.socket.on(eventName, (data: any) => {
        subscriber.next(data);
      });
    });
  }

  emit(eventName: string, data: any) {
    this.socket.emit(eventName, data);
  }

  close() {
    this.socket.close();
  }

}
