### ISSUE TITLE
Need Lazy Loading Support for Universal with Webpack

### ISSUE THREAD

**Issue by SwamyKottur** [angular/universal#946]
**Note: for support questions, please use one of [these channels][Channels]**. This repository's issues are reserved 
for feature requests and bug reports. Also, **Preboot has moved** [here][preboot] - please make preboot-related issues 
there.

* **I'm submitting a ...**
```
- [ ] feature request
```

* **What modules are related to this Issue?**
```
- [ ] express-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**

*feature*

* **What is the current behavior?**

With custom webpack lazy loading is not working in universal

* **If the current behavior is a bug**, please provide the steps to reproduce and if possible a minimal demo of the 
problem by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.2.0
- Browser: [all]
- Language: [all]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [ NodeJS ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by Toxicable** [comment]
We don't directly support Custom Webpack configs, there are far too many variables to account for that makes it a near impossible task.
We have provided API's that ensure Lazy Loading works with the CLI but it's hard to ensure that it will work with every custom webpack config.
You're welcome to try make those API's work with your setup but we cant provide support for it.
I'd suggest starting with an ejected CLI webpack config and go from there.

Due to the above im going to close this issue.
If you find any problems with the current API's then feel free to open an issue for it
